Repository nextcloud/deck, pull requests merged in 2018-11, with the labels that each got.

#648 Documentation
  docs/API-Nextcloud.md
  docs/API.md
  docs/Markdown.md
  docs/extra.css
  docs/index.md
  docs/resources/er-diagram.dia
  docs/resources/er-diagram.jpg
  docs/structure.md
  lib/Controller/AttachmentApiController.php
  mkdocs.yml
Labels: 2. developing, docs

#676 Do not call register for comment entities twice
  appinfo/app.php
  lib/AppInfo/Application.php
Labels: 3. to review, bug

#675 Fix activity view on 15
  js/controller/ActivityController.js
  templates/main.php
Labels: 3. to review, bug

#682 Only call fclose if resource is still available
  lib/Service/FileService.php
Labels: 3. to review, bug

#642 Checkbox fixes
  css/style.scss
  js/controller/BoardController.js
  js/controller/CardController.js
  js/legacy/markdown-it-checkbox.js
Labels: 2. developing, bug

#680 Replace subject parameters in plain subject string as well
  lib/Activity/DeckProvider.php
  tests/unit/Activity/ActivityManagerTest.php
  tests/unit/Activity/DeckProviderTest.php
Labels: 3. to review, bug

#681 Design fixes
  css/activity.css
  css/comp-13.scss
  css/icons.scss
  css/style.scss
  js/controller/ActivityController.js
  js/controller/CardController.js
  lib/Activity/DeckProvider.php
  templates/main.php
  templates/part.card.php
Labels: 2. developing

#695 Fix tab details alignment
  css/style.scss
  templates/part.card.php
Labels: 3. to review, bug, design

#699 Papercut: unify name of actions
  templates/part.board.headerControls.php
  templates/part.board.mainView.php
  templates/part.board.sidebarView.php
  templates/part.boardlist.php
  templates/part.card.attachments.php
  templates/part.navigation.php
Labels: 3. to review

#727 Fix relative timestamp and alignment in deleted items list
  css/style.scss
  templates/part.board.sidebarView.php
Labels: 3. to review, bug

#736 Remove card parameter when it's null
  lib/Activity/DeckProvider.php
  tests/unit/Activity/DeckProviderTest.php
Labels: 4. to release, bug

#738 Test compatibility with stable15
  .drone.yml
Labels: 3. to review, tests

#723 Deck now remembers the side menu state
  js/.jshintrc
  js/controller/AppController.js
Labels: 3. to review, design, enhancement
