Repository nextcloud/deck, pull requests merged in 2018-10, with the labels that each got.

#609 Printing CSS styles
  css/print.scss
  css/style.scss
Labels: 4. to release, enhancement

#632 Comments support
  appinfo/app.php
  appinfo/info.xml
  css/autocomplete.scss
  css/icons.scss
  css/style.scss
  img/description.svg
  js/app/App.js
  js/app/Run.js
  js/controller/ActivityController.js
  js/controller/BoardController.js
  js/directive/contenteditable.js
  js/legacy/commentcollection.js
  js/legacy/commentmodel.js
  js/legacy/commentsummarymodel.js
  js/legacy/jquery.atwho.min.js
  js/legacy/jquery.caret.min.js
  js/service/ActivityService.js
  lib/Activity/ActivityManager.php
  lib/Activity/CommentEventHandler.php
  lib/Activity/DeckProvider.php
  lib/AppInfo/Application.php
  lib/Db/Card.php
  lib/Notification/NotificationHelper.php
  lib/Notification/Notifier.php
  lib/Service/CardService.php
  lib/Service/StackService.php
  templates/main.php
  templates/part.board.mainView.php
  templates/part.card.activity.html
  templates/part.card.php
  tests/unit/Activity/CommentEventHandlerTest.php
  tests/unit/Activity/DeckProviderTest.php
  tests/unit/Db/CardTest.php
  tests/unit/Notification/NotificationHelperTest.php
  tests/unit/Notification/NotifierTest.php
  tests/unit/Service/CardServiceTest.php
Labels: 3. to review, enhancement

#639 Bugfix/noid/comment compatibility
  appinfo/info.xml
  css/comp-13.scss
  css/style.scss
  js/controller/ActivityController.js
  js/controller/BoardController.js
  js/controller/CardController.js
  js/service/ActivityService.js
  templates/part.board.sidebarView.php
  templates/part.card.activity.html
  templates/part.card.php
Labels: 3. to review, bug

#638 v0.5.0-beta1
  .drone.yml
  .travis.yml
  CHANGELOG.md
  appinfo/app.php
  appinfo/info.xml
  js/service/ActivityService.js
  lib/AppInfo/Application.php
Labels: 4. to release

#653 Fix comment mention subject
  lib/Notification/Notifier.php
  tests/unit/Notification/NotifierTest.php
Labels: 2. developing, bug

#641 General design improvements
  css/style.scss
  templates/part.board.headerControls.php
  templates/part.card.php
Labels: 3. to review, design

#656 consistent-pop-up
  templates/part.navigation.php
Labels: 3. to review, enhancement

#643 General styling and accessibility fixes
  css/icons.scss
  css/style.scss
  img/toggle-view-collapse.svg
  img/toggle-view-expand.svg
Labels: 3. to review, bug, design

#651 Fix webpack build with new CSP on 15
  js/init.js
  js/webpack.dev.config.js
Labels: 2. developing, bug
