Repository nextcloud/deck, pull requests merged in 2018-12, with the labels that each got.

#746 Added optional classes has-tasks, has-tasks-completed, overdue, now and
  templates/part.board.mainView.php
Labels: 3. to review, enhancement

#760 Use new search API when available
  js/directive/search.js
Labels: 3. to review, bug

#759 Do not show comments in board timeline
  js/service/ActivityService.js
Labels: 3. to review, bug

#761 Fix information in activity emails
  lib/Activity/ActivityManager.php
  lib/Activity/CommentEventHandler.php
  lib/Activity/DeckProvider.php
  tests/unit/Activity/CommentEventHandlerTest.php
  tests/unit/Activity/DeckProviderTest.php
Labels: 3. to review, bug

#753 Travis PHP 7.3 test
  .travis.yml
Labels: 2. developing, tests

#762 Add drone tests for PHP 7.3
  .drone.yml
Labels: 3. to review, tests

#709 Add dedicated setting for description change activities
  appinfo/database.xml
  appinfo/info.xml
  lib/Activity/ActivityManager.php
  lib/Activity/DescriptionSetting.php
  lib/Activity/Setting.php
  lib/Cron/CardDescriptionActivity.php
  lib/Db/Card.php
  lib/Db/CardMapper.php
  lib/Db/ChangeHelper.php
  lib/Service/CardService.php
  tests/unit/Activity/SettingTest.php
  tests/unit/Db/CardTest.php
Labels: 3. to review, enhancement

#765 Trigger comment notification on update only
  lib/Activity/CommentEventHandler.php
Labels: 3. to review, bug

#766 Use regular groups endpoint to support Nextcloud 13
  js/controller/ListController.js
  lib/Controller/ConfigController.php
  lib/Controller/PageController.php
  tests/unit/controller/PageControllerTest.php
Labels: 3. to review, bug

#764 Release 0.5.1
  CHANGELOG.md
  appinfo/info.xml
Labels: 2. developing, release

#735 Update ActivityManager.php
  lib/Activity/ActivityManager.php
Labels: 3. to review

#770 Check group limit in the proper way
  lib/Service/PermissionService.php
Labels: 3. to review, bug

#773 Use proper timezone and locale format for due date activities
  js/controller/ActivityController.js
  lib/Activity/DeckProvider.php
  templates/part.card.activity.html
  tests/unit/Activity/DeckProviderTest.php
Labels: 3. to review, bug

#777 Make new comment string translatable
  js/controller/ActivityController.js
  templates/part.card.activity.html
Labels: 3. to review

#774 Fix numeric types and missing card id in card detail results
  lib/Controller/BoardApiController.php
  lib/Controller/StackApiController.php
  lib/Db/AssignedUsers.php
  lib/Db/Label.php
  lib/Db/LabelMapper.php
Labels: 3. to review, bug

#813 Mark notification as read if a card with duedate gets archived
  lib/Notification/NotificationHelper.php
  lib/Service/CardService.php
Labels: 3. to review, bug
