Repository nextcloud/deck, pull requests merged in 2018-08, with the labels that each got.

#557 Feature/undo delete cards and stacks
  appinfo/database.xml
  appinfo/info.xml
  appinfo/routes.php
  css/style.scss
  js/controller/BoardController.js
  js/service/ApiService.js
  js/service/CardService.js
  js/service/StackService.js
  lib/Controller/CardController.php
  lib/Controller/StackController.php
  lib/Db/Card.php
  lib/Db/CardMapper.php
  lib/Db/LabelMapper.php
  lib/Db/Stack.php
  lib/Db/StackMapper.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  lib/Service/StackService.php
  templates/part.board.mainView.php
  templates/part.board.sidebarView.php
  tests/unit/Db/BoardMapperTest.php
  tests/unit/Db/CardTest.php
  tests/unit/Db/StackTest.php
  tests/unit/Service/CardServiceTest.php
  tests/unit/Service/StackServiceTest.php
  tests/unit/controller/CardControllerTest.php
  tests/unit/controller/StackControllerTest.php
Labels: 4. to release, enhancement

#592 editable inline card titles
  css/style.scss
  templates/part.board.mainView.php
Labels: 3. to review, design, enhancement, help wanted

#597 Fix some small accessibility issues
  templates/part.board.headerControls.php
  templates/part.board.mainView.php
Labels: 3. to review, enhancement
