Repository nextcloud/deck, pull requests merged in 2019-03, with the labels that each got.

#906 change timeline icon opacity
  css/style.scss
Labels: 3. to review, papercut

#814 Prevent duplicate tag names
  js/controller/BoardController.js
  js/service/ApiService.js
  lib/Service/LabelService.php
  templates/part.board.sidebarView.php
Labels: 4. to release, bug

#816 Fix duplicate call to delete
  lib/Service/BoardService.php
  templates/part.navigation.php
  tests/unit/Service/BoardServiceTest.php
Labels: 3. to review, bug

#937 Add proper annotations for assignUser
  lib/Controller/CardApiController.php
Labels: 3. to review, bug

#936 User documentation in english
  docs/DOCUMENTATION_en.md
  docs/resources/gifs/EN_archive.gif
  docs/resources/gifs/EN_create_board.gif
  docs/resources/gifs/EN_create_columns.gif
  docs/resources/gifs/EN_create_task.gif
  docs/resources/gifs/EN_put_infos.gif
  docs/resources/gifs/EN_put_infos_2.gif
Labels: 3. to review, docs, enhancement

#956 Add user docs to the navigation
  docs/User_documentation_en.md
  mkdocs.yml
Labels: 3. to review, docs

#922 Let ExceptionMiddleware properly return JSON on API related exceptions
  lib/AppInfo/Application.php
  lib/Middleware/ExceptionMiddleware.php
  tests/unit/Middleware/ExceptionMiddlewareTest.php
Labels: 3. to review, enhancement

#959 Fix activity text
  lib/Activity/ActivityManager.php
Labels: 3. to review, papercut

#946 Collaboration linking
  .drone.yml
  css/collections.css
  css/style.scss
  js/controller/BoardController.js
  js/init-collections.js
  js/init.js
  js/package-lock.json
  js/package.json
  js/views/BoardSelector.vue
  js/views/CollaborationView.vue
  js/webpack.config.js
  lib/AppInfo/Application.php
  lib/Collaboration/Resources/ResourceProvider.php
  lib/Service/BoardService.php
  lib/Service/PermissionService.php
  run-eslint.sh
  templates/main.php
  templates/part.board.sidebarView.php
Labels: 3. to review, enhancement

#923 Share with circles
  css/icons.scss
  css/style.scss
  img/circles.svg
  js/controller/BoardController.js
  js/service/BoardService.js
  lib/Db/Acl.php
  lib/Db/BoardMapper.php
  lib/Db/Circle.php
  lib/Service/BoardService.php
  lib/Service/PermissionService.php
  templates/part.board.sidebarView.php
  tests/unit/Service/BoardServiceTest.php
Labels: 3. to review, enhancement

#960 REST API enhancements
  appinfo/routes.php
  docs/API-Nextcloud.md
  docs/API.md
  lib/Controller/BoardApiController.php
  lib/Service/BoardService.php
Labels: 4. to release, enhancement, feature: api

#885 [nc16-only] Implementing fulltextsearch
  .drone.yml
  .gitignore
  appinfo/app.php
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Provider/DeckProvider.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  lib/Service/FullTextSearchService.php
  lib/Service/StackService.php
  tests/unit/Service/BoardServiceTest.php
  tests/unit/Service/CardServiceTest.php
  tests/unit/Service/StackServiceTest.php
Labels: 3. to review
