Repository nextcloud/deck, pull requests merged in 2019-02, with the labels that each got.

#886 Fix issues with duplicate polyfill added with 16
  appinfo/info.xml
  js/.babelrc.js
  js/webpack.config.js
Labels: 3. to review, backport-request, bug

#876 prevent loading details by clicking on the card title
  templates/part.board.mainView.php
Labels: 3. to review, enhancement

#873 Removed tooltips "Access for group" in board.sidebarView
  templates/part.board.sidebarView.php
Labels: 3. to review, papercut

#857 Use JS tooltips for board controls
  templates/part.board.headerControls.php
Labels: 4. to release, design, enhancement

#893 Bump master version for 0.6
  .drone.yml
  .travis.yml
  appinfo/info.xml
Labels: 3. to review, release

#739 Allow deck to be limited to groups again
  appinfo/info.xml
Labels: 3. to review, bug

#870 change UI after label has been changed
  js/controller/BoardController.js
Labels: 4. to release, bug
