Repository nextcloud/deck, pull requests merged in 2019-10, with the labels that each got.

#1257 Unify reorder results to always be an array
  lib/Service/CardService.php
Labels: 3. to review, backport-request, bug

#1221 Clone boards with stacks, labels
  appinfo/routes.php
  css/icons.scss
  img/clone.svg
  lib/Controller/BoardController.php
  lib/Service/BoardService.php
  src/components/navigation/AppNavigationBoard.vue
  src/services/BoardApi.js
  src/store/main.js
Labels: 4. to release, enhancement

#1242 move card to another board
  src/components/cards/CardItem.vue
  src/store/card.js
Labels: 3. to review, enhancement

#1293 Share boards and assign cards
  css/icons.scss
  lib/Service/PermissionService.php
  src/components/board/Board.vue
  src/components/board/BoardSidebar.vue
  src/components/board/SharingTabSidebar.vue
  src/components/board/TagsTabSidebar.vue
  src/components/board/TimelineTabSidebar.vue
  src/store/main.js
  src/store/stack.js
Labels: 4. to release, enhancement, vue-migration

#1255 Improvements to Card Heading Editing
  src/components/cards/CardItem.vue
Labels: 4. to release, enhancement

#1305 clip icon instead of folder icon
  css/icons.scss
  img/attach.svg
  src/components/card/CardSidebar.vue
Labels: 3. to review, design
