Repository nextcloud/deck, pull requests merged in 2019-05, with the labels that each got.

#1026 Fix acl update route
  appinfo/routes.php
Labels: 3. to review, bug

#1034 Only map circles if the app is enabled
  lib/Db/BoardMapper.php
Labels: 3. to review, bug

#1033 Do not fail if groups don't exist
  lib/Controller/ConfigController.php
Labels: 3. to review, bug

#1035 Cast entity to array when logging
  lib/Activity/ActivityManager.php
Labels: 2. developing

#1047 Expose app version through capabilities
  lib/AppInfo/Application.php
  lib/Capabilities.php
Labels: 3. to review, enhancement

#1049 returns string on null
  lib/Service/FullTextSearchService.php
Labels: 3. to review

#1062 Revert "Do not use getDisplayName for groups"
  lib/Db/Group.php
  tests/unit/Db/GroupTest.php
Labels: 3. to review, enhancement
