Repository nextcloud/deck, pull requests merged in 2019-04, with the labels that each got.

#985 Only try to add comment details if the comment was found
  lib/Activity/DeckProvider.php
Labels: 3. to review, bug

#984 Fix importing and comments css
  css/comments.scss
  css/comp-13.scss
  css/style.scss
  templates/main.php
Labels: 3. to review, bug

#986 Add lastModified field to labels
  appinfo/database.xml
  lib/Db/Label.php
  lib/Db/LabelMapper.php
  tests/unit/Db/LabelTest.php
Labels: 3. to review, enhancement

#987 Always use full owner details
  lib/Service/CardService.php
Labels: 3. to review, enhancement, feature: api

#983 Bugfix/980/fts argument type
  lib/AppInfo/Application.php
  lib/Service/FullTextSearchService.php
Labels: 3. to review, bug

#988 Bugfix/967/collections fixes
  js/controller/BoardController.js
  js/init-collections.js
  js/views/BoardSelector.vue
Labels: 3. to review, bug

#993 Fix sortable placehodler in compact mode
  css/compact-mode.scss
Labels: 3. to review, bug

#991 using fulltextsearchmanager::isAvailable()
  lib/AppInfo/Application.php
Labels: 2. developing, bug

#999 Make sure we always reset the comments collection if the id changes
  js/controller/ActivityController.js
Labels: 3. to review, bug

#997 Some activity hardening
  lib/Activity/ActivityManager.php
  lib/Activity/DeckProvider.php
  tests/unit/Activity/DeckProviderTest.php
Labels: 3. to review, bug

#1014 Add proper default value for since
  lib/Service/BoardService.php
Labels: 3. to review, bug

#1015 Only try to access angular instance if we are currently in deck
  js/views/BoardSelector.vue
Labels: 3. to review, bug

#1011 Fix use of renamed SharingMiddleware
  lib/AppInfo/Application.php
Labels: 3. to review, bug

#935 Label editing in board sidebar
  .drone.yml
  src/components/Sidebar.vue
  src/components/board/Board.vue
  src/components/board/BoardSidebar.vue
  src/components/board/DeletedTabSidebard.vue
  src/components/board/SharingTabSidebard.vue
  src/components/board/TagsTabSidebard.vue
  src/components/board/TimelineTabSidebard.vue
  src/mixins/color.js
  src/models/index.js
  src/services/BoardApi.js
  src/store/main.js
Labels: vue-migration
