Repository nextcloud/deck, pull requests merged in 2020-07, with the labels that each got.

#2116 Adjust navigation to new component slots
  src/components/navigation/AppNavigation.vue
Labels: 3. to review, bug

#2118 Cleanup unneeded cardId parameter
  lib/Controller/AttachmentApiController.php
  lib/Controller/AttachmentController.php
  lib/Service/AttachmentService.php
  lib/Service/PermissionService.php
  lib/Service/StackService.php
  tests/unit/Service/AttachmentServiceTest.php
  tests/unit/controller/AttachmentApiControllerTest.php
  tests/unit/controller/AttachmentControllerTest.php
Labels: 3. to review, bug

#2123 fix control tooltip
  src/components/Controls.vue
Labels: 2. developing, design

#2035 attach files in description
  src/components/AttachmentDragAndDrop.vue
  src/components/card/AttachmentList.vue
  src/components/card/CardSidebar.vue
  src/components/card/CardSidebarTabAttachments.vue
  webpack.js
Labels: 3. to review, enhancement

#1926 new filter: unassigned cards
  src/components/Controls.vue
  src/store/card.js
Labels: 3. to review, enhancement
