Repository nextcloud/deck, pull requests merged in 2020-10, with the labels that each got.

#2255 Use unified search events to apply on board filtering
  package-lock.json
  package.json
  src/main.js
Labels: 4. to release, bug

#2117 Activity fixes
  lib/Activity/ActivityManager.php
  lib/Activity/DeckProvider.php
  lib/Service/CardService.php
  tests/unit/Activity/DeckProviderTest.php
Labels: 2. developing, backport-request, bug, feature: activity

#2308 Prepare 1.1.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 2. developing, release

#2330 undo with toasts
  src/components/board/Stack.vue
  src/components/cards/CardMenu.vue
Labels: 3. to review, design, enhancement

#2363 Use uid instead of displayname for sharee results
  src/components/board/SharingTabSidebar.vue
Labels: 3. to review, backport-request, bug

#2361 Comments do not depend on the comments app
  src/components/card/CardSidebar.vue
Labels: 3. to review, backport-request

#2358 Properly check if FTSEvent has an argument set
  lib/Event/FTSEvent.php
Labels: 3. to review, backport-request, bug

#2359 Also exclude deleted items from calendar boards
  lib/Db/BoardMapper.php
Labels: 3. to review, backport-request, bug

#2367 Properly handle multiple shares in a row and refactor sharee loading
  src/components/board/SharingTabSidebar.vue
  src/store/main.js
Labels: 3. to review, backport-request, bug

#2434 Move most destructive actions in drop down menus to the bottom
  src/components/cards/CardMenu.vue
Labels: 3. to review, backport-request, bug, design

#2433 Fix scrollable titles with Dyslexia font
  src/components/cards/CardItem.vue
Labels: 3. to review, backport-request, bug

#2437 Only remove card padding for editable cards
  src/components/cards/AvatarList.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardItem.vue
  src/components/cards/CardMenu.vue
Labels: 3. to review, backport-request, bug, design

#2435 Do not open the dialog automatically upon card creation, only upon click
  src/App.vue
  src/components/board/Stack.vue
  src/components/card/CardSidebar.vue
  src/components/cards/CardItem.vue
Labels: 3. to review, backport-request, bug, design
