Repository nextcloud/deck, pull requests merged in 2020-04, with the labels that each got.

#1651 show if filter or archiv view is set
  src/components/Controls.vue
Labels: 3. to review, enhancement

#1629 Assign groups/circles to cards
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/Controller/CardApiController.php
  lib/Controller/CardController.php
  lib/Db/AssignedUsers.php
  lib/Db/AssignedUsersMapper.php
  lib/Db/BoardMapper.php
  lib/Db/Circle.php
  lib/Db/Group.php
  lib/Db/User.php
  lib/Event/FTSEvent.php
  lib/Migration/Version1000Date20200308073933.php
  lib/Service/AssignmentService.php
  lib/Service/CardService.php
  lib/Service/FullTextSearchService.php
  src/components/board/SharingTabSidebar.vue
  src/components/card/CardSidebar.vue
  src/components/card/CardSidebarTabComments.vue
  src/components/card/CommentForm.vue
  src/components/cards/AvatarList.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardItem.vue
  src/services/CardApi.js
  src/store/card.js
  src/store/main.js
  tests/integration/database/AssignedUsersMapperTest.php
  tests/unit/Db/GroupTest.php
  tests/unit/Db/UserTest.php
  tests/unit/Service/AssignmentServiceTest.php
  tests/unit/Service/CardServiceTest.php
  tests/unit/controller/CardApiControllerTest.php
  tests/unit/controller/CardControllerTest.php
Labels: 3. to review, enhancement

#1662 Properly update description and add autosave delay
  src/components/card/CardSidebar.vue
  src/components/cards/CardBadges.vue
Labels: 3. to review, bug

#1652 Progress indicator for attachment uploads
  package-lock.json
  package.json
  src/components/AttachmentDragAndDrop.vue
  src/components/card/CardSidebarTabAttachments.vue
  src/mixins/attachmentUpload.js
  src/services/AttachmentApi.js
  src/store/attachment.js
Labels: 3. to review, enhancement

#1656 Disable snap.js
  src/main.js
Labels: 3. to review, bug

#1653 Harden permission check on reshares
  lib/Service/BoardService.php
  tests/unit/Service/BoardServiceTest.php
Labels: 3. to review, backport-request, bug

#1669 Adjust card design
  package.json
  src/components/card/CardSidebar.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardItem.vue
Labels: 3. to review, design

#1670 Fix filtering and sorting of stacks that caused card reordering
  src/components/board/Stack.vue
  src/store/card.js
Labels: 3. to review, bug: regression

#1654 Prepare 1.0.0 Beta 1
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, release

#1706 changed names
  src/components/board/DeletedTabSidebar.vue
  src/components/board/TagsTabSidebar.vue
Labels: 3. to review

#1707 archived cards adjustments
  src/components/Controls.vue
  src/components/board/Stack.vue
Labels: 3. to review, bug

#1705 permissions added on board cloning
  lib/Service/BoardService.php
  package-lock.json
Labels: 3. to review, bug

#1713 fixed tooltip bug and closes #1679
  src/components/Controls.vue
  src/components/boards/BoardItem.vue
  src/components/navigation/AppNavigationBoard.vue
Labels: 3. to review, bug

#1725 Remove duplicate action button
  src/components/Controls.vue
Labels: 3. to review, technical debt

#1735 Use absolute urls for activity
  lib/Activity/DeckProvider.php
  tests/unit/Activity/DeckProviderTest.php
Labels: 0. Needs triage, 3. to review, bug

#1731 Use separate preview for description and allow toggling checkboxes
  package-lock.json
  package.json
  src/components/card/CardSidebar.vue
Labels: 3. to review, bug: regression

#1734 Hide comments tab if comments app is disabled
  src/components/card/CardSidebar.vue
Labels: 3. to review, bug

#1733 Let labels/assignedUsers have sane default values in the store
  src/store/card.js
Labels: 3. to review, bug: regression

#1728 Fix frontend urls
  lib/Notification/Notifier.php
  src/router.js
Labels: 3. to review, bug

#1727 Properly sort cards if order is the same
  lib/Db/CardMapper.php
  src/store/card.js
Labels: 3. to review, bug

#1732 Make settings menu more usable
  src/App.vue
  src/components/navigation/AppNavigation.vue
Labels: 3. to review, bug

#1737 Fix checkmark regex to apply for lists only
  src/components/cards/CardBadges.vue
Labels: 3. to review, bug

#1726 Fix searching for sharees
  package.json
  src/components/board/SharingTabSidebar.vue
  src/store/main.js
Labels: 4. to release, bug

#1730 Bump version to 1.0.0-beta2
  appinfo/info.xml
Labels: 3. to review, release

#1742 Always use server results from sharee search
  src/components/board/SharingTabSidebar.vue
Labels: 3. to review, bug

#1751 Add animations and pin create card input
  src/components/board/Board.vue
  src/components/board/Stack.vue
  src/components/card/CardSidebar.vue
  src/components/cards/CardItem.vue
  src/css/animations.scss
Labels: 3. to review, design, enhancement

#1739 Optimize filter icon
  img/filter.svg
Labels: 3. to review, bug

#1743 Filter board list by search box input
  src/components/boards/Boards.vue
Labels: 3. to review, bug

#1754 Fix month due date filter and make code a bit more readable
  src/components/Controls.vue
  src/store/card.js
Labels: 3. to review, bug

#1729 Add length documentation for title attributes in the API documentation
  docs/API.md
Labels: 3. to review, docs

#1741 Always set self/blob csp when displaying attachments
  lib/Service/FileService.php
  tests/unit/Service/FileServiceTest.php
Labels: 4. to release, bug

#1771 Add HMR with webpack-dev-server
  README.md
  lib/Controller/PageController.php
  package-lock.json
  package.json
  src/main.js
  webpack.dev.js
  webpack.hot.js
Labels: 3. to review

#1740 add attachments to desc
  package-lock.json
  src/components/board/Board.vue
  src/components/card/AttachmentList.vue
  src/components/card/CardSidebar.vue
  src/components/card/CardSidebarTabAttachments.vue
Labels: 4. to release, enhancement, high
