Repository nextcloud/deck, pull requests merged in 2020-08, with the labels that each got.

#2188 CardBadges: Count checkboxes started with "+ [ ]"
  src/components/cards/CardBadges.vue
Labels: 4. to release, bug

#1853 archive all cards from stack
  src/components/board/Stack.vue
Labels: 3. to review, enhancement

#1934 card dashboard
  appinfo/routes.php
  lib/Controller/OverviewApiController.php
  lib/Db/CardMapper.php
  lib/Service/CardService.php
  lib/Service/OverviewService.php
  src/components/Controls.vue
  src/components/board/Board.vue
  src/components/board/Stack.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardItem.vue
  src/components/cards/CardMenu.vue
  src/components/navigation/AppNavigation.vue
  src/components/overview/Overview.vue
  src/css/variables.scss
  src/router.js
  src/services/OverviewApi.js
  src/store/card.js
  src/store/main.js
  src/store/overview.js
  src/store/stack.js
Labels: 2. developing, enhancement

#2206 Fix read-only sidebar (fixes #2033)
  src/components/card/CardSidebar.vue
Labels: 3. to review, bug

#2208 Fix design, dark mode and keyboard navigation of the board list
  css/collections.css
  css/icons.scss
  package-lock.json
  package.json
  src/components/board/SharingTabSidebar.vue
  src/components/boards/BoardItem.vue
  src/components/boards/Boards.vue
  src/components/cards/CardItem.vue
Labels: 4. to release, bug

#2158 Fix description in dark mode
  src/components/card/CardSidebar.vue
Labels: 4. to release, bug, design

#2243 Various smaller styling fixes
  src/components/Controls.vue
  src/components/board/Stack.vue
  src/components/card/CardSidebar.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardItem.vue
  src/components/navigation/AppNavigation.vue
  src/components/navigation/AppNavigationBoardCategory.vue
Labels: 3. to review, bug, design

#2244 Toggle filter on clicking card labels
  src/components/cards/CardItem.vue
  src/store/main.js
Labels: 3. to review, enhancement
