Repository nextcloud/deck, pull requests merged in 2020-06, with the labels that each got.

#1925 Fix generated fronted urls
  lib/Activity/DeckProvider.php
  lib/Collaboration/Resources/ResourceProvider.php
  lib/Collaboration/Resources/ResourceProviderCard.php
  lib/Notification/Notifier.php
  lib/Provider/DeckProvider.php
  tests/unit/Activity/DeckProviderTest.php
Labels: 2. developing, bug: regression

#1976 Delete boards that users own once they are deleted
  lib/AppInfo/Application.php
  lib/Db/BoardMapper.php
Labels: 3. to review, bug

#1977 Redirect from previously used routes to the current ones
  src/router.js
Labels: 3. to review, bug

#1998 Add Checklist explaination to the doc
  docs/Markdown.md
Labels: 4. to release, docs

#2019 Remove old global css rule
  src/App.vue
Labels: 3. to review, bug, bug: regression

#2030 Build tarball on pull requests
  .github/workflows/appbuild.yml
Labels: 3. to review

#2022 Bugfix/1831/comments api
  docs/API.md
  lib/Controller/CommentsApiController.php
  lib/Service/CommentService.php
  src/services/CommentApi.js
Labels: 3. to review, bug, feature: api, feature: comments

#2020 Fix navigation issue with leftover nodes
  src/components/navigation/AppNavigation.vue
Labels: 3. to review, bug, bug: regression

#2027 Allow to unassign current user from card
  src/components/cards/CardMenu.vue
Labels: 3. to review, bug

#2021 Fix description issues
  src/components/card/CardSidebar.vue
  webpack.common.js
Labels: 3. to review, bug, bug: regression

#2045 Improve label styling
  src/components/board/TagsTabSidebar.vue
  src/components/card/CardSidebar.vue
  src/components/cards/CardItem.vue
Labels: 3. to review, bug, design

#2032 Force order by id as second sorting key
  lib/Db/StackMapper.php
Labels: 3. to review, bug

#2062 Fix saving card description after toggling checkboxes
  src/components/card/CardSidebar.vue
Labels: 3. to review, bug, bug: regression

#2065 Adding CSS rule for Markdown Blockquotes
  src/css/markdown.scss
Labels: 4. to release, bug

#2059 Fix fetching attachments on card change
  src/components/card/AttachmentList.vue
  src/components/card/CardSidebarTabAttachments.vue
  src/store/attachment.js
Labels: 3. to review, bug

#2060 Use mixing for relative date in card sidebar
  src/components/card/CardSidebar.vue
  src/store/card.js
Labels: 3. to review, bug

#2072 Bump version to 1.0.4
  CHANGELOG.md
  appinfo/info.xml
Labels: 2. developing, release
