Repository nextcloud/deck, pull requests merged in 2020-03, with the labels that each got.

#1579 Card store cleanup
  src/components/Controls.vue
  src/components/board/Stack.vue
  src/components/card/CardSidebar.vue
  src/components/cards/CardItem.vue
  src/main.js
  src/store/card.js
Labels: 3. to review, technical debt

#1577 Show tooltip with local timezone
  src/components/cards/CardBadges.vue
  src/main.js
Labels: 3. to review, bug

#1573 Move to database migrations
  appinfo/database.xml
  lib/Migration/Version1000Date20200306161713.php
Labels: 3. to review, enhancement

#1537 Comments reply
  .eslintrc.js
  appinfo/routes.php
  css/icons.scss
  docs/API.md
  img/reply.svg
  lib/AppInfo/Application.php
  lib/Controller/CommentsApiController.php
  lib/Middleware/ExceptionMiddleware.php
  lib/Service/CommentService.php
  package-lock.json
  package.json
  src/components/ActivityEntry.vue
  src/components/card/CardSidebarTabComments.vue
  src/components/card/CommentForm.vue
  src/components/card/CommentItem.vue
  src/css/comments.scss
  src/mixins/relativeDate.js
  src/services/BoardApi.js
  src/services/CardApi.js
  src/services/CommentApi.js
  src/services/StackApi.js
  src/store/comment.js
Labels: 3. to review, enhancement

#1574 Make sure due date is properly updated in the UI
  src/components/cards/CardBadges.vue
Labels: 3. to review, bug

#1576 Fix card sizing when editing
  src/components/cards/CardItem.vue
Labels: 3. to review, bug

#1575 Trashbin refactoring
  lib/Service/CardService.php
  src/components/board/DeletedTabSidebar.vue
  src/services/CardApi.js
  src/services/StackApi.js
  src/store/card.js
  src/store/main.js
  src/store/stack.js
  src/store/trashbin.js
Labels: 3. to review, bug

#1524 Attachments
  lib/Controller/AttachmentApiController.php
  lib/Controller/AttachmentController.php
  lib/Db/AttachmentMapper.php
  lib/Exceptions/ConflictException.php
  lib/Middleware/ExceptionMiddleware.php
  lib/Service/FileService.php
  package-lock.json
  package.json
  src/components/card/CardSidebarTabAttachments.vue
  src/components/cards/CardBadges.vue
  src/services/AttachmentApi.js
  src/store/attachment.js
  src/store/card.js
  src/store/main.js
  tests/unit/Service/FileServiceTest.php
Labels: 4. to release, enhancement

#1600 Add back initial state and check for filesize and canCreate permissions
  lib/Controller/PageController.php
  package-lock.json
  package.json
  src/components/card/CardSidebarTabAttachments.vue
  src/components/navigation/AppNavigation.vue
  tests/unit/controller/PageControllerTest.php
Labels: 3. to review, bug

#1601 drag and drop on attachment tab
  src/components/card/CardSidebar.vue
  src/components/card/CardSidebarTabAttachments.vue
Labels: 4. to release, enhancement

#1628 Fix showing cards after create
  src/components/cards/CardItem.vue
Labels: 3. to review, bug: regression

#1610 new mixin and component
  package-lock.json
  src/components/AttachmentDragAndDrop.vue
  src/components/card/CardSidebarTabAttachments.vue
  src/components/cards/CardItem.vue
  src/mixins/attachmentUpload.js
  src/store/card.js
Labels: 3. to review, enhancement

#1649 Do not get deleted cards when fetching overdue for notifications
  lib/Db/CardMapper.php
Labels: 3. to review, bug

#1648 Allow to set duedate during card creation
  docs/API.md
  lib/Controller/CardApiController.php
  lib/Service/CardService.php
Labels: 3. to review, bug
