Repository nextcloud/deck, pull requests merged in 2020-09, with the labels that each got.

#2047 show card details in modal
  src/App.vue
  src/components/card/CardSidebar.vue
  src/components/navigation/AppNavigation.vue
  src/store/main.js
Labels: 3. to review, enhancement

#2200 Unified search implementation
  appinfo/app.php
  appinfo/info.xml
  css/deck.scss
  lib/AppInfo/Application.php
  lib/AppInfo/Application20.php
  lib/AppInfo/ApplicationLegacy.php
  lib/Db/CardMapper.php
  lib/Db/StackMapper.php
  lib/Search/BoardSearchResultEntry.php
  lib/Search/CardSearchResultEntry.php
  lib/Search/DeckProvider.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  src/components/board/Stack.vue
  tests/integration/app/AppTest.php
Labels: 3. to review, enhancement

#2249 Bump version to 1.1.0-beta1
  CHANGELOG.md
  appinfo/info.xml
Labels: release

#2252 Fix double slash in the deck activity links
  lib/Activity/DeckProvider.php
Labels: 4. to release, bug

#2269 No need to add url-loader twice
  webpack.js
Labels: 3. to review, bug: regression

#2270 Fix empty content view to align with other widgets
  src/views/Dashboard.vue
Labels: 3. to review, bug

#2279 l10n:add translation to card placeholder
  src/components/board/Stack.vue
Labels: 3. to review, enhancement, translation

#2278 Fix wrong SQL queries
  lib/Db/CardMapper.php
Labels: 4. to release, bug, bug: regression

#2275 Wait for services to be registered before performing further setup that requires services
  lib/AppInfo/Application20.php
Labels: 3. to review, bug: regression

#2283 Do not handle exceptions from page controller in the ExceptionMiddleware
  lib/Middleware/ExceptionMiddleware.php
Labels: 3. to review, bug

#2282 Duedate picker fixes
  src/components/card/CardSidebar.vue
Labels: 3. to review, bug

#2298 Use absolute URLs for the search
  lib/Search/BoardSearchResultEntry.php
  lib/Search/CardSearchResultEntry.php
Labels: 3. to review, bug

#1545 Expose boards as calendars
  appinfo/info.xml
  appinfo/routes.php
  lib/Controller/ConfigController.php
  lib/Controller/PageController.php
  lib/DAV/Calendar.php
  lib/DAV/CalendarObject.php
  lib/DAV/CalendarPlugin.php
  lib/DAV/DeckCalendarBackend.php
  lib/Db/Card.php
  lib/Db/CardMapper.php
  lib/Db/DeckMapper.php
  lib/Db/Stack.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  lib/Service/ConfigService.php
  lib/Service/StackService.php
  src/components/navigation/AppNavigation.vue
  src/store/main.js
  tests/unit/controller/PageControllerTest.php
Labels: 3. to review, enhancement

#2250 Bump version to 1.1.0-beta2
  appinfo/info.xml
Labels: 2. developing, release

#2318 card title: prevent space and no text
  src/components/board/Stack.vue
  src/components/card/CardSidebar.vue
  src/components/cards/CardItem.vue
Labels: 3. to review, bug

#2271 sort tags in filter
  src/components/Controls.vue
  src/components/card/CardSidebar.vue
  src/components/cards/CardItem.vue
Labels: 3. to review, bug

#2319 Move style loading to BeforeTemplateRenderedEvent
  lib/AppInfo/Application20.php
  lib/Listeners/BeforeTemplateRenderedListener.php
Labels: 3. to review, bug

#2320 consistent naming
  src/App.vue
  src/components/Controls.vue
  src/components/board/Board.vue
  src/components/navigation/AppNavigationAddBoard.vue
Labels: 3. to review, design
