Repository nextcloud/deck, pull requests merged in 2020-02, with the labels that each got.

#1508 Comments
  package-lock.json
  package.json
  src/components/ActivityEntry.vue
  src/components/card/CardSidebarTabComments.vue
  src/components/card/CommentForm.vue
  src/components/card/CommentItem.vue
  src/components/cards/CardBadges.vue
  src/helpers/mentions.js
  src/helpers/xml.js
  src/services/BoardApi.js
  src/services/CommentApi.js
  src/services/StackApi.js
  src/store/comment.js
  src/store/main.js
Labels: 3. to review, enhancement

#1516 Properly sort cards in the frontend
  src/components/board/Stack.vue
  src/store/card.js
Labels: 3. to review, bug, bug: regression

#1511 search cards (title and description)
  src/main.js
  src/store/card.js
  src/store/main.js
Labels: 2. developing, enhancement, vue-migration

#1525 Fix undefined users variable
  lib/Service/PermissionService.php
Labels: 3. to review, backport-request, bug

#1527 More github actions
  .drone.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  composer.json
Labels: 2. developing, tests

#1507 Board filter
  css/icons.scss
  img/filter.svg
  package-lock.json
  src/components/Controls.vue
  src/components/cards/CardItem.vue
  src/mixins/labelStyle.js
  src/store/card.js
  src/store/main.js
Labels: 3. to review, enhancement

#1529 l10n: Fixed typo
  src/components/Controls.vue
Labels: bug

#1530 Check for board membership on comments entity event
  lib/AppInfo/Application.php
Labels: backport-request, bug, bug: security

#1528 reduce card spacing
  src/components/board/Board.vue
  src/components/cards/CardItem.vue
Labels: 4. to release, design

#1562 fixed issue #834
  src/components/board/Stack.vue
  src/components/cards/CardItem.vue
Labels: 3. to review, bug
