Repository nextcloud/deck, pull requests merged in 2020-01, with the labels that each got.

#1434 Merge pull request #1434 from 4workers/insensitive-search
  js/filters/cardSearchFilter.js
Labels: 4. to release, enhancement

#1395 Limit card assignment to users who are participants of the board
  Makefile
  docs/API.md
  lib/Service/CardService.php
  lib/Service/PermissionService.php
  tests/integration/database/AssignedUsersMapperTest.php
  tests/unit/Service/CardServiceTest.php
Labels: 3. to review, bug, feature: api

#1454 Merge pull request #1454 from nextcloud/release/0.8.0
  CHANGELOG.md
  appinfo/info.xml
  js/package-lock.json
Labels: 3. to review, release

#1235 Comments
  package-lock.json
  package.json
  src/components/ActivityEntry.vue
  src/components/card/CardSidebar.vue
  src/components/card/CardSidebarTabActivity.vue
  src/components/card/CardSidebarTabAttachments.vue
  src/components/card/CardSidebarTabComments.vue
  src/components/card/CommentItem.vue
  src/css/comments.scss
  src/helpers/xml.js
  src/services/CommentApi.js
  src/store/comment.js
  src/store/main.js
Labels: 2. developing, 3. to review, vue-migration

#1483 Cleanup
  Makefile
  appinfo/routes.php
  package-lock.json
  package.json
  src/BoardSelector.vue
  src/CardSelector.vue
  src/components/Controls.vue
  src/components/board/Board.vue
  src/components/board/BoardSidebar.vue
  src/components/board/SharingTabSidebar.vue
  src/components/board/Stack.vue
  src/components/board/TagsTabSidebar.vue
  src/components/card/CardSidebar.vue
  src/components/cards/CardItem.vue
  src/components/navigation/AppNavigation.vue
  src/components/navigation/AppNavigationBoard.vue
  src/services/BoardApi.js
  src/services/CardApi.js
  src/services/CommentApi.js
  src/services/StackApi.js
  src/store/main.js
  templates/part.board.headerControls.php
  templates/part.board.mainView.php
  templates/part.board.sidebarView.php
  templates/part.boardlist.php
  templates/part.card.activity.html
  templates/part.card.attachments.php
  templates/part.card.php
  templates/part.navigation.php
  templates/part.settings.php
Labels: 3. to review

#1481 Fix dark mode shadow and markdown docs link (fix #1136)
  src/components/board/Stack.vue
  src/components/card/CardSidebar.vue
  src/components/cards/CardItem.vue
Labels: 3. to review, bug

#1492 Merge pull request #1492 from nextcloud/enh/application-cleanup
  appinfo/app.php
  lib/AppInfo/Application.php
  lib/Controller/PageController.php
  lib/Middleware/DefaultBoardMiddleware.php
  lib/Service/BoardService.php
  lib/Service/DefaultBoardService.php
  tests/unit/Service/DefaultBoardServiceTest.php
  tests/unit/controller/PageControllerTest.php
Labels: 3. to review, enhancement

#1482 Bump version and fix wording (fixes #1088)
  appinfo/info.xml
  src/components/Controls.vue
  src/components/board/Stack.vue
Labels: 3. to review, enhancement

#1503 Run nightly build on github actions
  .github/workflows/nightly.yml
  .nextcloudignore
  Makefile
  README.md
  krankerl.toml
Labels: 3. to review, release

#1505 use color picker from nextcloud vue
  package-lock.json
  package.json
  src/components/ColorPicker.vue
  src/components/board/BoardSidebar.vue
  src/components/board/TagsTabSidebar.vue
  src/components/card/CardSidebar.vue
  src/components/navigation/AppNavigationAddBoard.vue
  src/components/navigation/AppNavigationBoard.vue
Labels: 4. to release, bug
