Repository nextcloud/deck, pull requests merged in 2021-06, with the labels that each got.

#3092 Refactor update to have proper order of optional parameters
  lib/Controller/CardApiController.php
  lib/Controller/CardController.php
  lib/Service/CardService.php
  tests/psalm-baseline.xml
  tests/unit/Service/CardServiceTest.php
  tests/unit/controller/CardControllerTest.php
Labels: 3. to review, bug

#3090 [stable1.2] Always fetch attachments
  src/components/card/AttachmentList.vue
Labels: 3. to review, bug

#3142 Always pass user id in share provider
  lib/Sharing/DeckShareProvider.php
Labels: 3. to review, backport-request, bug

#2854 add card button in card overview
  src/CardCreateDialog.vue
  src/components/Controls.vue
Labels: 4. to release, enhancement

#3147 Add card button to the dashboard widget
  src/views/Dashboard.vue
Labels: 4. to release, enhancement

#3105 Circles 22
  lib/Db/Circle.php
  lib/Service/PermissionService.php
Labels: 3. to review, bug

#3152 Only offer stack creation in emptycontent with proper permissions
  src/components/board/Board.vue
Labels: 3. to review, backport-request, bug
