Repository nextcloud/deck, pull requests merged in 2021-09, with the labels that each got.

#3294 Fix print style issues
  css/print.scss
Labels: bug, 2. developing, backport-request

#3299 Return false instead of throwing when getting calendar setting
  lib/Service/ConfigService.php
Labels: bug, 3. to review, high, bug: regression

#3298 Delete file shares through attachments API
  docs/API.md
  lib/Service/AttachmentService.php
  lib/Service/FilesAppService.php
  src/components/card/AttachmentList.vue
Labels: bug, 3. to review, feature: attachments

#2791 Open description links in new tab
  package-lock.json
  package.json
  src/components/card/Description.vue
Labels: enhancement, 3. to review

#3316 Additional check for stacks
  lib/Service/CardService.php
  lib/Service/StackService.php
Labels: backport-request
