Repository nextcloud/deck, pull requests merged in 2021-12, with the labels that each got.

#3487 l10n: Change to a capital letter
  appinfo/info.xml
Labels: translation

#3498 Update composer config
  composer.json
  composer.lock
Labels: bug, 3. to review

#3429 Store cardDetailsInModal in config instead of state
  docs/API.md
  lib/Service/ConfigService.php
  src/App.vue
  src/components/board/Stack.vue
  src/components/card/CardSidebar.vue
  src/components/card/CardSidebarTabDetails.vue
  src/components/card/Description.vue
  src/components/navigation/AppNavigation.vue
  src/store/main.js
Labels: enhancement, 4. to release

#3501 Add a missing translation - not found in transifex
  src/components/cards/CardMenu.vue
Labels: bug, 4. to release

#3182 Import from Trello
  appinfo/info.xml
  appinfo/routes.php
  composer.json
  composer.lock
  docs/API.md
  docs/User_documentation_en.md
  docs/implement-import.md
  docs/import-class-diagram.md
  docs/resources/BoardImport.svg
  docs/resources/BoardImport.yuml
  lib/Command/BoardImport.php
  lib/Controller/BoardImportApiController.php
  lib/Event/ABoardImportGetAllowedEvent.php
  lib/Event/BoardImportGetAllowedEvent.php
  lib/Service/FileService.php
  lib/Service/Importer/ABoardImportService.php
  lib/Service/Importer/BoardImportCommandService.php
  lib/Service/Importer/BoardImportService.php
  lib/Service/Importer/Systems/TrelloApiService.php
  lib/Service/Importer/Systems/TrelloJsonService.php
  lib/Service/Importer/fixtures/config-trelloApi-schema.json
  lib/Service/Importer/fixtures/config-trelloJson-schema.json
  mkdocs.yml
  tests/data/config-trelloJson.json
  tests/data/data-trelloJson.json
  tests/unit/Command/BoardImportTest.php
  tests/unit/Service/Importer/BoardImportServiceTest.php
  tests/unit/Service/Importer/Systems/TrelloJsonServiceTest.php
  tests/unit/controller/BoardImportApiControllerTest.php
Labels: enhancement, 4. to release
