Repository nextcloud/deck, pull requests merged in 2021-11, with the labels that each got.

#3384 Keep exceptions http response generic
  lib/Middleware/ExceptionMiddleware.php
  lib/StatusException.php
  tests/unit/Middleware/ExceptionMiddlewareTest.php
Labels: 3. to review, technical debt

#2710 Due date shortcuts in the datepicker
  src/components/card/CardSidebarTabDetails.vue
Labels: enhancement, 3. to review

#3420 Update npm and node engines versions
  package.json
Labels: dependencies

#3432 Fix event name for updating the description
  src/components/card/Description.vue
Labels: bug, 3. to review, bug: regression

#3428 Allow to download an attachment without navigating to the files app
  src/components/card/AttachmentList.vue
Labels: bug, 3. to review, feature: attachments

#3365 Switch to QBMapper in BoardMapper
  lib/Db/BoardMapper.php
  tests/psalm-baseline.xml
Labels: enhancement, 4. to release, technical debt, php

#3444 Cache most frequent queries
  lib/Collaboration/Resources/ResourceProvider.php
  lib/Collaboration/Resources/ResourceProviderCard.php
  lib/Db/Board.php
  lib/Db/BoardMapper.php
  lib/Db/CardMapper.php
  lib/Service/BoardService.php
  lib/Service/PermissionService.php
  tests/unit/Db/BoardTest.php
Labels: 3. to review, backport-request, performance

#3459 Fix cursor generation if no results are found
  lib/Search/DeckProvider.php
Labels: bug, 3. to review

#3458 Fix overview card listing
  lib/Db/Board.php
  tests/unit/Db/BoardMapperTest.php
Labels: bug, 3. to review, backport-request, bug: regression
