Repository nextcloud/deck, pull requests merged in 2021-04, with the labels that each got.

#2946 [stable1.3] fix desc save bug
  src/components/card/CardSidebarTabDetails.vue
  src/components/card/Description.vue
Labels: 3. to review, bug

#2947 [stable1.2] fix desc save bug
  src/components/card/CardSidebarTabDetails.vue
  src/components/card/Description.vue
Labels: 1. to develop, bug

#2964 Fix navigating to board details
  src/components/navigation/AppNavigationBoard.vue
Labels: 3. to review, backport-request, bug

#2933 Move full text search to proper events
  lib/AppInfo/Application.php
  lib/AppInfo/Application20.php
  lib/AppInfo/ApplicationLegacy.php
  lib/Event/AAclEvent.php
  lib/Event/ACardEvent.php
  lib/Event/AclCreatedEvent.php
  lib/Event/AclDeletedEvent.php
  lib/Event/AclUpdatedEvent.php
  lib/Event/CardCreatedEvent.php
  lib/Event/CardDeletedEvent.php
  lib/Event/CardUpdatedEvent.php
  lib/Listeners/FullTextSearchEventListener.php
  lib/Service/AssignmentService.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  lib/Service/FullTextSearchService.php
  lib/Service/StackService.php
  tests/psalm-baseline.xml
  tests/unit/Service/BoardServiceTest.php
  tests/unit/Service/StackServiceTest.php
Labels: 3. to review, technical debt

#2983 Fix codemirror description width
  src/components/card/Description.vue
Labels: 3. to review, backport-request, bug

#2989 Fix unified comments search with postgres
  lib/Db/CardMapper.php
  tests/integration/config/behat.yml
  tests/integration/features/bootstrap/BoardContext.php
  tests/integration/features/bootstrap/CommentContext.php
  tests/integration/features/bootstrap/SearchContext.php
  tests/integration/features/search.feature
Labels: 3. to review, bug

#2935 Rich object string parameters for notifications
  lib/Notification/Notifier.php
  tests/unit/Notification/NotifierTest.php
Labels: 4. to release, enhancement

#2950 Remove notification on unshare and add type hints
  lib/Notification/NotificationHelper.php
  lib/Service/AssignmentService.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  tests/unit/Notification/NotificationHelperTest.php
Labels: 3. to review, backport-request, bug

#3003 Only import debounce
  src/components/board/SharingTabSidebar.vue
Labels: 3. to review, technical debt

#3005 Do not query the lookupserver when looking for sharees
  src/store/main.js
Labels: 3. to review, backport-request, bug

#3010 Remove app code check
  .github/workflows/app-code-check.yml
Labels: backport-request, tests

#3011 l10n: Spelling unification
  src/components/cards/AvatarList.vue
Labels: 4. to release, bug, translation

#3022 Migrate to babel config and updgrade webpack-vue-config
  .eslintrc.js
  babel.config.js
  lib/AppInfo/Application.php
  lib/Dashboard/DeckWidget.php
  lib/Listeners/BeforeTemplateRenderedListener.php
  package-lock.json
  package.json
  src/components/ActivityEntry.vue
  src/components/card/CommentForm.vue
  src/components/cards/AvatarList.vue
  src/components/navigation/AppNavigationBoard.vue
  src/mixins/color.js
  src/views/Dashboard.vue
  templates/main.php
  webpack.js
Labels: 3. to review, dependencies

#3025 Show comment counter and highlight if unread comments are available
  css/icons.scss
  lib/Db/Card.php
  lib/Service/CardService.php
  src/components/cards/CardBadges.vue
  tests/unit/Db/CardTest.php
  tests/unit/Service/CardServiceTest.php
Labels: 3. to review, bug

#3014 Proper error handling when fetching comments fails
  css/icons.scss
  lib/Db/Card.php
  lib/Service/CardService.php
  src/components/card/CardSidebarTabComments.vue
  src/components/card/CommentForm.vue
  src/components/card/CommentItem.vue
  src/components/cards/CardBadges.vue
  src/css/comments.scss
  src/services/CommentApi.js
  tests/unit/Db/CardTest.php
  tests/unit/Service/CardServiceTest.php
Labels: 3. to review, backport-request, bug

#3030 Proper error handling when fetching comments fails
  css/icons.scss
  lib/Db/Card.php
  lib/Service/CardService.php
  src/components/card/CardSidebarTabComments.vue
  src/components/card/CommentForm.vue
  src/components/card/CommentItem.vue
  src/components/cards/CardBadges.vue
  src/css/comments.scss
  tests/unit/Db/CardTest.php
  tests/unit/Service/CardServiceTest.php
Labels: 3. to review, bug
