Repository nextcloud/deck, pull requests merged in 2021-02, with the labels that each got.

#2772 Add API to register card actions
  src/components/card/CardSidebar.vue
  src/main.js
  src/store/actions.js
  src/store/main.js
  src/store/stack.js
Labels: 3. to review, enhancement

#2793 fix desc save bug
  src/components/card/CardSidebarTabDetails.vue
  src/components/card/Description.vue
Labels: 3. to review, bug

#2812 Fix issues when creating a card from a talk message
  lib/Controller/CardController.php
  src/CardCreateDialog.vue
Labels: 3. to review, backport-request, bug

#2822 Also include /apps/spreed urls in the listener for loading the talk integration
  lib/Listeners/BeforeTemplateRenderedListener.php
Labels: 3. to review, backport-request, bug
