Repository nextcloud/deck, pull requests merged in 2022-12, with the labels that each got.

#4326 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4314 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4315 Fix component renaming so that acl works on shares again
  src/components/board/SharingTabSidebar.vue
Labels: bug, 4. to release

#4342 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3065 Export Board
  .eslintrc.js
  appinfo/routes.php
  cypress.config.js
  l10n/fr.json
  lib/Controller/BoardController.php
  lib/Service/BoardService.php
  src/components/navigation/AppNavigationBoard.vue
  src/services/BoardApi.js
  tests/unit/Service/BoardServiceTest.php
Labels: enhancement, 3. to review

#4341 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
