Repository nextcloud/deck, pull requests merged in 2022-04, with the labels that each got.

#3601 Add support for PHP 8.1
  .github/dependabot.yml
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .github/workflows/phpunit.yml
  lib/Activity/ChangeSet.php
  lib/Db/Board.php
  lib/Db/Card.php
  lib/Db/CardMapper.php
  lib/Db/LabelMapper.php
  lib/Db/RelationalEntity.php
  lib/Db/RelationalObject.php
  lib/Db/Stack.php
  lib/Service/CardService.php
  lib/StatusException.php
  tests/integration/composer.json
  tests/unit/Activity/ActivityManagerTest.php
Labels: 3. to review, technical debt

#3689 Fix cron jobs
  lib/Cron/CardDescriptionActivity.php
  lib/Cron/DeleteCron.php
  lib/Cron/ScheduledNotifications.php
  tests/unit/Cron/DeleteCronTest.php
  tests/unit/Cron/ScheduledNoificationsTest.php
Labels: 3. to review, bug: regression

#3695 Update master php testing versions
  tests/phpunit.integration.xml
  tests/phpunit.xml
Labels: tests, 4. to release

#3690 Optimise queries when preparing card related notifications
  lib/Db/Stack.php
  lib/Db/StackMapper.php
  lib/Notification/Notifier.php
  tests/unit/Notification/NotifierTest.php
Labels: 3. to review, technical debt

#3670 Properly check for the stack AND setting board permissions
  lib/Service/StackService.php
  tests/unit/Service/StackServiceTest.php
Labels: 3. to review, backport-request, bug: regression

#3712 Remove unused argument from transfer ownership
  src/store/main.js
Labels: bug, 3. to review

#3625 Fix: Check all circle shares for permissions
  lib/Service/PermissionService.php
Labels: bug, 3. to review, backport-request

#3665 [stable22] Transfer ownership
  .github/workflows/lint.yml
  Makefile
  appinfo/info.xml
  appinfo/routes.php
  composer.json
  composer.lock
  docs/User_documentation_en.md
  lib/Command/TransferOwnership.php
  lib/Controller/BoardController.php
  lib/Db/AclMapper.php
  lib/Db/AssignmentMapper.php
  lib/Db/BoardMapper.php
  lib/Db/CardMapper.php
  lib/Service/BoardService.php
  lib/Service/PermissionService.php
  src/components/board/SharingTabSidebar.vue
  src/components/cards/CardMenu.vue
  src/store/main.js
  tests/integration/database/TransferOwnershipTest.php
  tests/integration/run.sh
  tests/unit/Activity/ActivityManagerTest.php
  tests/unit/Cron/DeleteCronTest.php
  tests/unit/Cron/ScheduledNoificationsTest.php
  tests/unit/Notification/NotificationHelperTest.php
  tests/unit/Service/AttachmentServiceTest.php
  tests/unit/Service/BoardServiceTest.php
  tests/unit/Service/PermissionServiceTest.php
Labels: enhancement, 3. to review

#3683 Fix paramter replacements when creating deck cards from talk messages
  src/init-talk.js
Labels: bug, frontend, 3. to review, backport-request, integration

#3497 [stable23] Use explicit cast to make use of index
  lib/Sharing/DeckShareProvider.php
  psalm.xml
Labels: bug, 3. to review, backport-request, performance

#3692 Fix hidden attachment icon on archived cards
  lib/Service/StackService.php
Labels: bug, 3. to review

#3681 Show cards after moving into another list
  src/components/cards/CardMenu.vue
  src/store/card.js
Labels: bug, 3. to review

#3743 [stable22] add autofocus on board edit #3326
  src/components/navigation/AppNavigationBoard.vue
Labels: bug, 3. to review

#3742 [stable22] Fix paramter replacements when creating deck cards from talk messages
  src/init-talk.js
Labels: bug, 3. to review

#3741 [stable23] Fix paramter replacements when creating deck cards from talk messages
  src/init-talk.js
Labels: bug, 3. to review

#3745 Add missing indices
  lib/Migration/Version10800Date20220422061816.php
  tests/psalm-baseline.xml
Labels: 3. to review, backport-request, performance

#3753 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#3761 Fix text selection in dark mode and modal view
  src/components/card/CardSidebar.vue
  src/components/card/Description.vue
Labels: bug, 3. to review, backport-request

#3769 Handle qb mapper exception messages properly
  lib/Db/AttachmentMapper.php
Labels: bug, 3. to review, backport-request
