Repository nextcloud/deck, pull requests merged in 2022-09, with the labels that each got.

#4014 disable Create card button while no stack is chosen
  src/CardCreateDialog.vue
Labels: 3. to review

#4036 Fix attachment creator name: show display name
  lib/Service/AttachmentService.php
  src/components/card/AttachmentList.vue
  tests/unit/Service/AttachmentServiceTest.php
Labels: bug, 3. to review, backport-request, feature: attachments

#4031 Implement card reference widget
  .eslintrc.js
  lib/AppInfo/Application.php
  lib/Reference/CardReferenceProvider.php
  package-lock.json
  package.json
  src/App.vue
  src/CardCreateDialog.vue
  src/components/ActivityEntry.vue
  src/components/ActivityList.vue
  src/components/AttachmentDragAndDrop.vue
  src/components/Controls.vue
  src/components/board/Board.vue
  src/components/board/BoardSidebar.vue
  src/components/board/DeletedTabSidebar.vue
  src/components/board/Stack.vue
  src/components/board/TagsTabSidebar.vue
  src/components/board/TimelineTabSidebar.vue
  src/components/boards/Boards.vue
  src/components/card/AttachmentList.vue
  src/components/card/CardSidebar.vue
  src/components/card/CardSidebarTabActivity.vue
  src/components/card/CardSidebarTabAttachments.vue
  src/components/card/CardSidebarTabComments.vue
  src/components/card/CardSidebarTabDetails.vue
  src/components/card/CommentForm.vue
  src/components/card/CommentItem.vue
  src/components/card/Description.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardItem.vue
  src/components/icons/DeckIcon.vue
  src/components/navigation/AppNavigation.vue
  src/components/navigation/AppNavigationBoardCategory.vue
  src/components/overview/Overview.vue
  src/components/search/GlobalSearchResults.vue
  src/init-card-reference.js
  src/init-collections.js
  src/init-dashboard.js
  src/init-talk.js
  src/main.js
  src/mixins/labelStyle.js
  src/router.js
  src/services/BoardApi.js
  src/services/StackApi.js
  src/store/attachment.js
  src/store/card.js
  src/store/comment.js
  src/store/main.js
  src/store/overview.js
  src/store/stack.js
  src/store/trashbin.js
  src/views/CardReferenceWidget.vue
  src/views/Dashboard.vue
  src/views/FileSharingPicker.js
  webpack.js
Labels: enhancement, frontend, 3. to review

#4000 Add related resources panel to board sharing tab sidebar
  src/components/board/SharingTabSidebar.vue
Labels: 2. developing

#4033 Implement new dashboard widget interfaces
  lib/Dashboard/DeckWidget.php
  src/views/Dashboard.vue
Labels: enhancement, 3. to review, feature: api

#4069 Reference widget adjustments for Text
  src/init-card-reference.js
  src/views/CardReferenceWidget.vue
Labels: 3. to review, integration

#4066 Fix deleteAcl
  lib/Reference/CardReferenceProvider.php
  lib/Service/BoardService.php
  tests/unit/Service/BoardServiceTest.php
  tests/unit/controller/BoardControllerTest.php
Labels: bug, 3. to review, backport-request

#4071 Use global import for nextcloud-vue
  src/BoardSelector.vue
  src/CardCreateDialog.vue
  src/CardSelector.vue
  src/components/board/SharingTabSidebar.vue
  src/components/card/AttachmentList.vue
  src/init-card-reference.js
  src/views/Dashboard.vue
Labels: bug, 3. to review

#4077 use OCP\Collaboration\Reference\Reference
  lib/Reference/CardReferenceProvider.php
Labels: 3. to review, backport-request
