Repository nextcloud/deck, pull requests merged in 2022-08, with the labels that each got.

#3926 [stable23] Switch to 'markdown-it-task-checkbox' for rendering of task lists
  package-lock.json
  package.json
  src/components/card/Description.vue
Labels: bug, 3. to review

#3925 [stable24] Switch to 'markdown-it-task-checkbox' for rendering of task lists
  package-lock.json
  package.json
  src/components/card/Description.vue
Labels: bug, 3. to review

#3953 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#3952 Fetch attachment folder for the correct user during cron job
  lib/Service/ConfigService.php
  lib/Sharing/Listener.php
Labels: bug, 3. to review

#3958 Update npm and node engines versions
  package.json
Labels: dependencies

#3980 Use capped memory cache for board permissions
  lib/Service/PermissionService.php
Labels: 3. to review, performance

#3982 Improve CalDAV integration performance
  lib/DAV/Calendar.php
  lib/Db/CardMapper.php
Labels: 3. to review, performance

#3984 Hide deprecated projects in sidebar and card details by default
  src/components/board/SharingTabSidebar.vue
  src/components/card/CardSidebarTabDetails.vue
Labels: 3. to review

#3991 Update to @nextcloud/vue@6.0.0-beta.4
  cypress/e2e/boardFeatures.js
  cypress/e2e/cardFeatures.js
  cypress/e2e/deckDashboard.js
  cypress/e2e/stackFeatures.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/utils/index.js
  package-lock.json
  package.json
  src/App.vue
  src/BoardSelector.vue
  src/CardCreateDialog.vue
  src/CardSelector.vue
  src/components/ActivityEntry.vue
  src/components/AttachmentDragAndDrop.vue
  src/components/Controls.vue
  src/components/board/Board.vue
  src/components/board/BoardSidebar.vue
  src/components/board/SharingTabSidebar.vue
  src/components/board/Stack.vue
  src/components/board/TagsTabSidebar.vue
  src/components/boards/BoardItem.vue
  src/components/card/AttachmentList.vue
  src/components/card/CardSidebar.vue
  src/components/card/CardSidebarTabComments.vue
  src/components/card/CardSidebarTabDetails.vue
  src/components/card/CommentForm.vue
  src/components/card/CommentItem.vue
  src/components/card/Description.vue
  src/components/cards/AvatarList.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardMenu.vue
  src/components/icons/DeckIcon.vue
  src/components/navigation/AppNavigation.vue
  src/components/navigation/AppNavigationAddBoard.vue
  src/components/navigation/AppNavigationBoard.vue
  src/components/navigation/AppNavigationBoardCategory.vue
  src/components/search/GlobalSearchResults.vue
  src/main.js
  src/views/Dashboard.vue
Labels: 3. to review, dependencies

#3983 Simpify query for getting shared files
  .github/workflows/integration.yml
  lib/Db/BoardMapper.php
  lib/Service/OverviewService.php
  lib/Sharing/DeckShareProvider.php
Labels: 3. to review, performance 🚀

#4013 release/1.8.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: release
