Repository nextcloud/deck, pull requests merged in 2022-07, with the labels that each got.

#3833 Fix for issue #3637
  src/css/markdown.scss
Labels: bug, 3. to review

#3898 Switch to 'markdown-it-task-checkbox' for rendering of task lists
  package-lock.json
  package.json
  src/components/card/Description.vue
Labels: bug, 3. to review

#3872 fix(docs): fix links to JSON schemas for Trello
  docs/User_documentation_en.md
Labels: 4. to release, docs

#3868 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#3818 Move to OCP\Collaboration\Resources\LoadAdditionalScriptsEvent
  composer.lock
  lib/Controller/PageController.php
  templates/main.php
Labels: 3. to review

#3910 Limit php tests to certain fails on pull requests
  .github/workflows/appbuild.yml
  .github/workflows/integration.yml
  .github/workflows/phpunit.yml
Labels: tests, 3. to review

#3916 Prevent opening card and applyLabelFilter on card drag end
  src/components/board/Stack.vue
  src/components/cards/CardItem.vue
Labels: bug, frontend, 3. to review

#3813 Make rename functions accessibly by keyboard navigation
  src/components/board/Board.vue
  src/components/board/Stack.vue
  src/components/cards/CardItem.vue
Labels: bug, 3. to review, accessibility

#3924 Set ids to skip to content/navigation
  lib/Controller/PageController.php
Labels: bug, 3. to review, accessibility

#3803 SCSS cleanup
  css/deck.css
  css/deck.scss
  css/globalstyles.scss
  css/icons.scss
  img/activity-dark.svg
  img/activity.svg
  img/archive-white.svg
  img/archive.svg
  img/circles-dark.svg
  img/circles.svg
  img/clone.svg
  img/reply.svg
  package-lock.json
  package.json
  src/App.vue
  src/components/Controls.vue
  src/components/board/Stack.vue
  src/components/card/CardSidebar.vue
  src/components/card/CommentItem.vue
  src/components/card/Description.vue
  src/components/cards/AvatarList.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardMenu.vue
  src/components/navigation/AppNavigation.vue
  src/components/navigation/AppNavigationBoard.vue
  src/components/navigation/AppNavigationBoardCategory.vue
  templates/main.php
Labels: 3. to review, technical debt, bug: regression

#3938 Fix tests running against 25 with adjusted ISimpleFile methods
  tests/unit/Service/FileServiceTest.php
Labels: 3. to review

#3862 Inserted required property in the rename list field, to prevent the l…
  lib/Service/StackService.php
  src/components/board/Stack.vue
Labels: bug, frontend, 3. to review

#3939 Invert icons properly in dark mode
  css/deck.css
Labels: bug, 3. to review

#3942 Fix share provider for master changes
  lib/Sharing/DeckShareProvider.php
Labels: bug, 3. to review
