Repository nextcloud/deck, pull requests merged in 2022-11, with the labels that each got.

#4182 [stable24] disables autocomplete on card creation
  src/components/cards/CardItem.vue
Labels: bug, 3. to review

#2272 click outside to close sidebar
  src/components/Sidebar.vue
Labels: enhancement, 2. developing

#4189 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4188 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4191 Move all to @nextcloud/vue-richtext
  package-lock.json
  package.json
  src/components/ActivityEntry.vue
  src/components/card/CommentItem.vue
  src/components/search/GlobalSearchResults.vue
Labels: bug, 3. to review

#4074 Improve stack drag and drop behavior
  src/components/board/Board.vue
  src/components/board/Stack.vue
Labels: enhancement, 3. to review

#4196 Add missing userId property
  lib/Reference/CardReferenceProvider.php
Labels: bug, backport-request

#4183 [stable23] disables autocomplete on card creation
  src/components/cards/CardItem.vue
Labels: bug, 3. to review

#4180 minor style fixes
  src/components/card/AttachmentList.vue
  src/components/card/Description.vue
Labels: bug, design, 4. to release

#3598 Handle circle deletion event
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Db/AclMapper.php
  lib/Listeners/ParticipantCleanupListener.php
  lib/Listeners/ResourceListener.php
  lib/Migration/DeletedCircleCleanup.php
  tests/psalm-baseline.xml
  tests/stub.phpstub
  tests/unit/Service/BoardServiceTest.php
Labels: bug, 3. to review

#4207 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4208 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4209 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4278 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
