Repository nextcloud/deck, pull requests merged in 2022-03, with the labels that each got.

#3552 return the selector for collections
  src/init-collections.js
Labels: bug, 4. to release, backport-request

#3628 Release 1.4.8
  .github/workflows/integration.yml
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: release

#3629 Release 1.5.6
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: release

#3630 Release 1.6.1
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: release

#3635 🐛 Fix missing files sidebar
  src/components/Sidebar.vue
  src/main.js
Labels: bug, 4. to release, backport-request

#3653 🚸 Shows error on board fetchData
  src/components/board/Board.vue
  src/helpers/errors.js
Labels: bug, enhancement, 3. to review

#2496 Transfer ownership
  Makefile
  appinfo/info.xml
  appinfo/routes.php
  composer.json
  composer.lock
  docs/User_documentation_en.md
  lib/Command/TransferOwnership.php
  lib/Controller/BoardController.php
  lib/Db/AclMapper.php
  lib/Db/AssignmentMapper.php
  lib/Db/BoardMapper.php
  lib/Db/CardMapper.php
  lib/Service/BoardService.php
  lib/Service/PermissionService.php
  src/components/board/SharingTabSidebar.vue
  src/store/main.js
  tests/integration/database/TransferOwnershipTest.php
  tests/integration/run.sh
  tests/unit/Activity/ActivityManagerTest.php
  tests/unit/Cron/DeleteCronTest.php
  tests/unit/Cron/ScheduledNoificationsTest.php
  tests/unit/Notification/NotificationHelperTest.php
  tests/unit/Service/AttachmentServiceTest.php
  tests/unit/Service/BoardServiceTest.php
  tests/unit/Service/PermissionServiceTest.php
Labels: enhancement, 3. to review, backport-request

#3650 Handle description shortening more gracefully
  lib/Activity/ActivityManager.php
  tests/unit/Activity/ActivityManagerTest.php
Labels: bug, 4. to release

#3560 Sort boards non case sensitive
  src/components/navigation/AppNavigationBoardCategory.vue
Labels: bug, 4. to release, backport-request

#3666 l10n: Delete space
  src/components/board/SharingTabSidebar.vue
Labels: translation
