Repository nextcloud/deck, pull requests merged in 2023-11, with the labels that each got.

#5257 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5258 add support for bidi text
  cypress/e2e/deckDashboard.js
  src/components/Controls.vue
  src/components/board/DeletedTabSidebar.vue
  src/components/board/Stack.vue
  src/components/card/CommentForm.vue
  src/components/card/CommentItem.vue
  src/components/card/Description.vue
  src/components/cards/CardItem.vue
  src/components/dashboard/Card.vue
  src/components/navigation/AppNavigationBoard.vue
Labels: enhancement, 3. to review

#5260 fix: Avoid too large index on postgres as indexing just the last_editor column is enough
  appinfo/info.xml
  lib/Db/CardMapper.php
  lib/Migration/Version1011Date20231106160059.php
  lib/Migration/Version10800Date20220422061816.php
Labels: bug, 3. to review, backport-request

#5262 fix: Check both card reference url patterns
  lib/Reference/CardReferenceProvider.php
  tests/unit/Reference/CardReferenceProviderTest.php
Labels: bug, 3. to review, backport-request

#5275 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5276 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5277 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5278 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5279 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5264 Card layout polishing
  cypress/e2e/cardFeatures.js
  src/components/board/Board.vue
  src/components/board/Stack.vue
  src/components/card/AttachmentList.vue
  src/components/cards/AvatarList.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardCover.vue
  src/components/cards/CardItem.vue
  src/components/cards/CardMenu.vue
  src/components/cards/badges/Done.vue
  src/components/cards/badges/DueDate.vue
  src/css/labels.scss
  src/css/variables.scss
Labels: bug, design, 3. to review

#5280 Issue triage fix collection
  lib/Dashboard/DeckWidgetToday.php
  lib/Dashboard/DeckWidgetTomorrow.php
  src/App.vue
  src/components/ActivityEntry.vue
  src/components/ActivityList.vue
  src/components/board/Stack.vue
  src/components/board/TagsTabSidebar.vue
  src/components/card/CardSidebar.vue
  src/components/card/CardSidebarTabDetails.vue
  src/components/card/Description.vue
  src/components/cards/CardItem.vue
  src/components/cards/CardMenu.vue
  src/components/cards/CardMenuEntries.vue
Labels: bug, 2. developing, backport-request

#5281 perf: Already pass board list as initial state
  appinfo/routes.php
  lib/Controller/PageController.php
  lib/Reference/BoardReferenceProvider.php
  lib/Reference/CardReferenceProvider.php
  src/App.vue
  src/components/navigation/AppNavigationBoardCategory.vue
  src/router.js
  src/store/main.js
  tests/unit/Reference/CardReferenceProviderTest.php
  tests/unit/controller/PageControllerTest.php
Labels: 3. to review, performance 🚀

#5282 feat: Move to contenteditable for inline title editing
  src/components/cards/CardItem.vue
Labels: enhancement, 3. to review

#5287 fix: Properly get done state for dav
  lib/Db/Card.php
Labels: bug, 3. to review

#5290 Fix upcoming cards and label input
  cypress/e2e/cardFeatures.js
  cypress/e2e/deckDashboard.js
  src/components/card/AssignmentSelector.vue
  src/components/card/Description.vue
  src/components/card/DueDateSelector.vue
  src/components/card/TagSelector.vue
  src/store/overview.js
Labels: bug, 3. to review

#5292 fix: Bring back due date indicator to compact mode
  src/components/cards/CardItem.vue
Labels: bug, 3. to review

#5293 scroll board by dragging
  src/components/board/Board.vue
  src/components/board/Stack.vue
Labels: enhancement, 2. developing, papercut

#5294 fix: Use text content as result for comments
  src/components/card/CommentForm.vue
Labels: bug, 3. to review, backport-request

#5309 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5296 Fix small issues around delete/undo
  lib/Collaboration/Resources/ResourceProvider.php
  lib/Db/BoardMapper.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  lib/Service/PermissionService.php
  src/components/board/Board.vue
  src/components/cards/CardMenuEntries.vue
  tests/unit/Activity/ActivityManagerTest.php
Labels: bug, 3. to review

#5299 fix(controls): use primary when filter is active
  src/components/Controls.vue
Labels: design, 4. to release, papercut

#5328 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5329 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
