Repository nextcloud/deck, pull requests merged in 2023-07, with the labels that each got.

#4900 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4874 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4875 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4873 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4872 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4871 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4899 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4908 fix(notification): Prevent null in parameters
  lib/Notification/Notifier.php
Labels: bug, 3. to review

#4718 Refactors controllers by using PHP8's constructor property promotion.
  lib/Controller/AttachmentApiController.php
  lib/Controller/AttachmentController.php
  lib/Controller/BoardApiController.php
  lib/Controller/BoardController.php
  lib/Controller/BoardImportApiController.php
  lib/Controller/CardApiController.php
  lib/Controller/CardController.php
  lib/Controller/CommentsApiController.php
  lib/Controller/ConfigController.php
  lib/Controller/LabelApiController.php
  lib/Controller/LabelController.php
  lib/Controller/OverviewApiController.php
  lib/Controller/PageController.php
  lib/Controller/SearchController.php
  lib/Controller/SessionController.php
  lib/Controller/StackApiController.php
  lib/Controller/StackController.php
Labels: 2. developing, technical debt

#4936 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4937 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4947 chore(composer): Update and cleanup composer dependencies
  composer.json
  composer.lock
  lib/Capabilities.php
  psalm.xml
Labels: 3. to review, dependencies

#4903 feat: Use user display name cache
  lib/Db/User.php
  lib/Service/CommentService.php
  lib/Service/SearchService.php
  tests/unit/Db/UserTest.php
Labels: 3. to review, technical debt

#4906 fix: Split query to fetch board ids to avoid slow query join
  lib/Db/BoardMapper.php
Labels: bug, 3. to review, performance 🚀

#4955 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4957 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4956 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4958 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4960 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4961 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4959 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4950 [stable26] fix: Split query to fetch board ids to avoid slow query join
  lib/Db/BoardMapper.php
Labels: bug, 3. to review, performance 🚀

#4949 [stable27] fix: Split query to fetch board ids to avoid slow query join
  lib/Db/BoardMapper.php
Labels: bug, 3. to review, performance 🚀

#4965 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
