Repository nextcloud/deck, pull requests merged in 2023-01, with the labels that each got.

#4350 fix(Sidebar): Only close sidebar on v-click-outside for specific targets
  cypress/e2e/boardFeatures.js
  cypress/e2e/cardFeatures.js
  cypress/e2e/deckDashboard.js
  cypress/e2e/sharingFeatures.js
  cypress/e2e/stackFeatures.js
  cypress/support/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/utils/sampleBoard.js
  src/components/Sidebar.vue
  src/components/board/Board.vue
  src/components/board/SharingTabSidebar.vue
  src/components/board/Stack.vue
  src/store/main.js
Labels: bug, 3. to review

#3876 basic notify_push usage with session handling
  appinfo/info.xml
  appinfo/routes.php
  docs/API.md
  lib/AppInfo/Application.php
  lib/Controller/SessionController.php
  lib/Cron/SessionsCleanup.php
  lib/Db/Board.php
  lib/Db/Session.php
  lib/Db/SessionMapper.php
  lib/Event/SessionClosedEvent.php
  lib/Event/SessionCreatedEvent.php
  lib/Listeners/LiveUpdateListener.php
  lib/Migration/Version10900Date202206151724222.php
  lib/NotifyPushEvents.php
  lib/Service/BoardService.php
  lib/Service/SessionService.php
  package-lock.json
  package.json
  src/components/Controls.vue
  src/components/SessionList.vue
  src/components/board/Board.vue
  src/main.js
  src/services/SessionApi.js
  src/sessions.js
  tests/integration/config/behat.yml
  tests/integration/features/acl.feature
  tests/integration/features/bootstrap/BoardContext.php
  tests/integration/features/bootstrap/ServerContext.php
  tests/integration/features/bootstrap/SessionContext.php
  tests/integration/features/sessions.feature
  tests/stub.phpstub
  tests/unit/Db/BoardTest.php
  tests/unit/Service/BoardServiceTest.php
Labels: enhancement, 4. to release

#4370 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4371 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4385 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4398 Update signature of Entity::markFieldUpdated
  lib/Db/RelationalEntity.php
Labels: 3. to review, bug: regression

#4415 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
