Repository nextcloud/deck, pull requests merged in 2023-06, with the labels that each got.

#4750 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#4800 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4801 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4802 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4772 fix: Allow dynamic autoloading for classes added during upgrade
  composer.json
Labels: bug, 3. to review, backport-request

#4828 doc: mention QOwnNotes integration
  README.md
Labels: docs

#4816 fix: crash when leaving out system parameter
  lib/Service/Importer/BoardImportService.php
Labels: 3. to review, backport-request, bug: regression

#4836 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#4854 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4853 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4852 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4855 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4851 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4830 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
