Repository nextcloud/deck, pull requests merged in 2023-09, with the labels that each got.

#5083 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5082 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5081 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5045 feat: Enhance dark mode
  package-lock.json
  package.json
  src/components/cards/CardItem.vue
  src/components/cards/badges/DueDate.vue
  src/mixins/color.js
Labels: bug, 3. to review

#5115 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5116 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5096 fix: export doesn't handle lists with no cards
  src/services/BoardApi.js
Labels: bug, 2. developing

#5131 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
