Repository nextcloud/deck, pull requests merged in 2023-10, with the labels that each got.

#5193 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5192 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5194 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5168 Board creation limitation : More understandable wordings
  src/components/navigation/AppNavigation.vue
Labels: 3. to review

#5164 Replace "Timeline" wording with "Activity" in order to be consistent with equivalent contexts throughout Nextcloud
  src/components/board/BoardSidebar.vue
  src/components/card/CardSidebar.vue
Labels: 3. to review, feature: activity

#5210 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5209 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5208 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5207 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5035 Card Cover Images
  src/components/Controls.vue
  src/components/cards/CardCover.vue
  src/components/cards/CardItem.vue
  src/store/main.js
Labels: enhancement, 3. to review

#2658 Upcoming/Today/Tomorrow dashboard widgets
  l10n/de_DE.json
  lib/AppInfo/Application.php
  lib/Dashboard/DeckWidgetToday.php
  lib/Dashboard/DeckWidgetTomorrow.php
  lib/Dashboard/DeckWidgetUpcoming.php
  src/components/dashboard/Card.vue
  src/init-dashboard.js
  src/store/overview.js
  src/views/DashboardToday.vue
  src/views/DashboardTomorrow.vue
  src/views/DashboardUpcoming.vue
Labels: enhancement, 4. to release

#5229 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5231 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5232 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5230 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5234 chore(php): Add PHP 8.3 to test matrix
  .github/workflows/lint-php.yml
  .github/workflows/phpunit.yml
Labels: 3. to review, technical debt

#5248 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5246 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5247 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
