Repository nextcloud/deck, pull requests merged in 2023-08, with the labels that each got.

#4994 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4995 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4993 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4996 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4992 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4997 fix: Use typed share event
  composer.lock
  lib/Sharing/Listener.php
Labels: bug, 3. to review

#4969 feat: create new card from smart picker
  lib/AppInfo/Application.php
  lib/Controller/CardApiController.php
  lib/Controller/CardController.php
  lib/Reference/CardReferenceProvider.php
  lib/Reference/CreateCardReferenceProvider.php
  src/CardCreateDialog.vue
  src/components/AttachmentDragAndDrop.vue
  src/components/Controls.vue
  src/components/card/AssignmentSelector.vue
  src/components/card/AttachmentList.vue
  src/components/card/CardSidebarTabDetails.vue
  src/components/card/Description.vue
  src/components/card/DueDateSelector.vue
  src/components/card/TagSelector.vue
  src/css/selector.scss
  src/init-reference.js
  src/views/CreateNewCardCustomPicker.vue
  src/views/Dashboard.vue
  tests/stub.phpstub
Labels: 3. to review

#4998 fix: Adapt regex for trello token to new length and format
  lib/Service/Importer/fixtures/config-trelloApi-schema.json
Labels: bug, 3. to review

#4939 enh/import from deck
  docs/export-import.md
  lib/Command/BoardImport.php
  lib/Command/UserExport.php
  lib/Db/Assignment.php
  lib/Db/BoardMapper.php
  lib/Db/LabelMapper.php
  lib/Db/RelationalEntity.php
  lib/Service/Importer/ABoardImportService.php
  lib/Service/Importer/BoardImportCommandService.php
  lib/Service/Importer/BoardImportService.php
  lib/Service/Importer/Systems/DeckJsonService.php
  lib/Service/Importer/Systems/TrelloJsonService.php
  lib/Service/Importer/fixtures/config-deckJson-schema.json
  tests/data/config-deckJson.json
  tests/data/deck.json
  tests/integration/database/TransferOwnershipTest.php
  tests/integration/import/ImportExportTest.php
  tests/phpunit.integration.xml
  tests/stub.phpstub
  tests/unit/Command/UserExportTest.php
  tests/unit/Service/Importer/BoardImportServiceTest.php
  tests/unit/Service/Importer/Systems/DeckJsonServiceTest.php
Labels: enhancement, 3. to review, backport-request

#5023 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5025 test: add cypress tests for create new deck card
  cypress/e2e/cardFeatures.js
Labels: tests, 3. to review

#5024 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5029 feat: error msg on CreateNewCardCustomPicker & only show available bo…
  src/views/CreateNewCardCustomPicker.vue
Labels: 3. to review

#5022 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5041 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4850 Remove duplicate button
  src/components/navigation/AppNavigationBoard.vue
Labels: 3. to review, backport-request

#4362 Enabled advanced fields option on tag color picker
  src/components/board/TagsTabSidebar.vue
Labels: enhancement, 4. to release

#5046 feat: remember last board, list for new card dialog
  cypress/e2e/cardFeatures.js
  src/components/card/CardSidebarTabDetails.vue
  src/views/CreateNewCardCustomPicker.vue
Labels: enhancement, 2. developing

#5070 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5047 feat: update smart picker links
  lib/Search/CardSearchResultEntry.php
Labels: 3. to review
