Repository nextcloud/deck, pull requests merged in 2023-02, with the labels that each got.

#4399 feat(Description): Use text as editor if available
  .github/workflows/cypress.yml
  cypress/e2e/cardFeatures.js
  cypress/support/commands.js
  cypress/utils/sampleBoard.js
  lib/Controller/PageController.php
  src/App.vue
  src/components/card/Description.vue
Labels: enhancement, 3. to review

#4440 perf: Lazy load dashboard components
  src/init-dashboard.js
Labels: 3. to review, performance 🚀

#4439 perf: Register notifier and resource listener lazy
  lib/AppInfo/Application.php
  lib/Listeners/ResourceAdditionalScriptsListener.php
Labels: 3. to review, performance 🚀

#3793 Optimise upcomming overview creation
  lib/Db/Card.php
  lib/Db/RelationalEntity.php
  lib/Model/BoardSummary.php
  lib/Model/CardDetails.php
  lib/Service/OverviewService.php
  src/components/overview/Overview.vue
  src/store/overview.js
  tests/psalm-baseline.xml
Labels: 4. to release, performance 🚀

#4465 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4452 Performance boost
  .github/workflows/integration.yml
  lib/Controller/BoardApiController.php
  lib/DAV/DeckCalendarBackend.php
  lib/Db/AclMapper.php
  lib/Db/AssignmentMapper.php
  lib/Db/BoardMapper.php
  lib/Db/CardMapper.php
  lib/Db/DeckMapper.php
  lib/Db/LabelMapper.php
  lib/Db/RelationalObject.php
  lib/Db/StackMapper.php
  lib/Db/User.php
  lib/Event/AAclEvent.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  lib/Service/DefaultBoardService.php
  lib/Service/OverviewService.php
  lib/Service/PermissionService.php
  lib/Service/SearchService.php
  lib/Service/StackService.php
  tests/integration/base-query-count.txt
  tests/integration/features/bootstrap/ServerContext.php
  tests/integration/run.sh
  tests/unit/Db/UserTest.php
  tests/unit/Notification/NotificationHelperTest.php
  tests/unit/Service/CardServiceTest.php
  tests/unit/Service/DefaultBoardServiceTest.php
  tests/unit/Service/Importer/Systems/TrelloJsonServiceTest.php
  tests/unit/Service/PermissionServiceTest.php
  tests/unit/Service/StackServiceTest.php
  tests/unit/controller/BoardControllerTest.php
Labels: 3. to review, performance 🚀

#4485 fix: Pass user id along to properly check permissions in background jobs
  lib/Service/PermissionService.php
Labels: bug, 3. to review

#4488 fix: Avoid mutating the due date when calculating days
  lib/Db/Card.php
Labels: bug, 3. to review, regression, 26 feedback

#4487 fix: Use passed userid when getting attachment folder
  lib/Service/ConfigService.php
Labels: bug, 3. to review
