Repository nextcloud/deck, pull requests merged in 2023-03, with the labels that each got.

#4490 fix: Use proper z-index for text menubar
  src/components/card/Description.vue
Labels: bug, 3. to review, 26 feedback

#4509 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#4514 fix(references): Mute NoPermissionException as it is expected to happen for references
  lib/Reference/BoardReferenceProvider.php
  lib/Reference/CardReferenceProvider.php
  lib/Reference/CommentReferenceProvider.php
Labels: bug, 3. to review, backport-request

#4518 fix(API): Fix board API details parameter to work as expected
  lib/Controller/BoardApiController.php
Labels: 3. to review, backport-request, feature: api, bug: regression

#4512 fix(cards): Fix card sizing by limiting too wide style rules
  src/components/board/Board.vue
Labels: bug, 3. to review, 26 feedback

#4530 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4552 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4553 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4551 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4560 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4561 fix: Adapt NcEmptyContent usages to new slots
  src/CardCreateDialog.vue
  src/components/board/Board.vue
Labels: bug, 3. to review, backport-request

#4566 Gracefully handle not found card for a share
  lib/Sharing/ShareAPIHelper.php
Labels: bug, 2. developing, backport-request
