Repository nextcloud/deck, pull requests merged in 2023-05, with the labels that each got.

#4643 fix: Append datetime picker to body to avoid cut off
  src/components/card/CardSidebarTabDetails.vue
Labels: bug, 3. to review, backport-request

#4642 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4641 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4640 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4639 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4648 Refactors lib\Activity\DeckProvider.php to improve code readability.
  lib/Activity/DeckProvider.php
Labels: 4. to release, technical debt

#4650 [stable26] chore: Remove unused @nextcloud/vue-dashboard
  package-lock.json
  package.json
  src/init-dashboard.js
  src/store/dashboard.js
Labels: bug, 3. to review

#4657 Converts 'strpos()' calls to improve code readability.
  lib/Controller/AttachmentController.php
  lib/Db/RelationalEntity.php
  lib/Listeners/BeforeTemplateRenderedListener.php
  lib/Listeners/ResourceAdditionalScriptsListener.php
  lib/Middleware/ExceptionMiddleware.php
  lib/Search/FilterStringParser.php
  lib/Validators/BaseValidator.php
  tests/unit/Activity/ActivityManagerTest.php
Labels: 4. to release, technical debt

#4682 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4681 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#4680 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#4673 Use the color-primary-element* variables
  src/App.vue
  src/BoardSelector.vue
  src/components/AttachmentDragAndDrop.vue
  src/components/card/Description.vue
  src/components/cards/CardBadges.vue
  src/components/cards/badges/DueDate.vue
Labels: bug, design, 3. to review

#4715 tests(phpunit): Run phpunit tests against PHP 8.2
  .github/workflows/phpunit.yml
Labels: tests, 3. to review, backport-request

#4746 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated
