Repository nextcloud/deck, pull requests merged in 2023-12, with the labels that each got.

#5344 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5343 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5351 fix: Get proper rich object for card actions
  cypress/e2e/cardFeatures.js
  src/components/card/CardSidebar.vue
  src/components/cards/CardMenuEntries.vue
Labels: bug, 3. to review

#3758 Keyboard shortcuts
  README.md
  src/App.vue
  src/components/Controls.vue
  src/components/KeyboardShortcuts.vue
  src/components/board/Board.vue
  src/components/cards/CardItem.vue
  src/components/modals/HelpModal.vue
  src/components/navigation/AppNavigation.vue
  src/store/card.js
  src/store/main.js
  src/views/CreateNewCardCustomPicker.vue
Labels: enhancement, 3. to review

#5371 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5372 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5388 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5399 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5400 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5402 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#5401 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated
