Repository nextcloud/deck, pull requests merged in 2024-05, with the labels that each got.

#5745 fix: permission check for cloning board
  lib/Service/BoardService.php
  src/components/navigation/AppNavigationBoard.vue
Labels: bug, 3. to review

#5848 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5797 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#5796 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#5850 Completed card button wording change
  src/components/card/DueDateSelector.vue
Labels: 3. to review, feature: modal, ux

#5612 Cleaning up unused indicies
  lib/Migration/Version1000Date20200306161713.php
  lib/Migration/Version11000Date20240222115515.php
Labels: bug, 2. developing

#5858 fix: card details focus issue with screen reader
  src/components/card/CardSidebar.vue
Labels: bug, 3. to review

#5722 Change import command's config default argument
  lib/Command/BoardImport.php
Labels: bug, 3. to review

#5882 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5881 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5883 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5884 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5907 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5937 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
