Repository nextcloud/deck, pull requests merged in 2024-10, with the labels that each got.

#6386 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6384 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6388 fix(changelog): Typo fix in 1.14.1 entry
  CHANGELOG.md
Labels: bug, 3. to review

#6385 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6412 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6391 [stable28] Avoid sql error on ONLY_FULL_GROUP_BY
  lib/Db/CardMapper.php
Labels: bug, backport-request

#6413 ci: fix cypress test
  cypress/support/commands.js
Labels: tests

#6416 feat: Add markdown support for comments
  src/components/card/CommentForm.vue
  src/components/card/CommentItem.vue
  src/css/comments.scss
Labels: enhancement, 3. to review, feature: comments

#6410 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6411 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6421 [stable30] chore(dev-deps): Bump nextcloud/ocp package
  .github/workflows/integration.yml
  composer.lock
Labels: 3. to review

#6422 chore(dev-deps): Bump nextcloud/ocp package
  composer.lock
Labels: 3. to review

#6447 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
