Repository nextcloud/deck, pull requests merged in 2024-11, with the labels that each got.

#6450 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6449 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6448 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6374 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6469 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6496 fix: two close buttons on card modal
  src/components/card/CardSidebar.vue
Labels: bug, 3. to review

#6491 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6519 chore: Add CODEOWNERS with current app maintainers
  .github/CODEOWNERS
Labels: 3. to review

#6471 fix(sharing): list accounts with matches in email
  cypress/e2e/sharingFeatures.js
  cypress/support/commands.js
  src/components/board/SharingTabSidebar.vue
Labels: bug, 3. to review

#6490 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6549 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6548 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
