Repository nextcloud/deck, pull requests merged in 2024-01, with the labels that each got.

#5423 Fix deleted card/board issues
  .github/workflows/integration.yml
  composer.json
  lib/Activity/ActivityManager.php
  lib/Activity/DeckProvider.php
  lib/Db/Card.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  lib/Service/CommentService.php
  lib/Service/PermissionService.php
  lib/Sharing/ShareAPIHelper.php
  tests/integration/features/acl.feature
  tests/integration/features/bootstrap/AttachmentContext.php
  tests/integration/features/bootstrap/BoardContext.php
  tests/integration/features/bootstrap/CommentContext.php
  tests/integration/features/bootstrap/ServerContext.php
  tests/integration/features/decks.feature
  tests/unit/Activity/DeckProviderTest.php
Labels: bug, 3. to review

#5434 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5436 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5438 [stable27] fix: allow null label colors in trello json importer
  lib/Activity/ActivityManager.php
  lib/Activity/CommentEventHandler.php
  lib/Activity/DeckProvider.php
  lib/AppInfo/Application.php
  lib/Controller/AttachmentApiController.php
  lib/Controller/BoardApiController.php
  lib/Controller/CardApiController.php
  lib/Controller/CardController.php
  lib/Controller/ConfigController.php
  lib/Controller/LabelApiController.php
  lib/Controller/LabelController.php
  lib/Controller/PageController.php
  lib/Controller/SessionController.php
  lib/Controller/StackApiController.php
  lib/Controller/StackController.php
  lib/Cron/CardDescriptionActivity.php
  lib/Cron/DeleteCron.php
  lib/Cron/ScheduledNotifications.php
  lib/Cron/SessionsCleanup.php
  lib/Db/BoardMapper.php
  lib/Db/ChangeHelper.php
  lib/Db/StackMapper.php
  lib/Listeners/LiveUpdateListener.php
  lib/Middleware/ExceptionMiddleware.php
  lib/Reference/BoardReferenceProvider.php
  lib/Reference/CardReferenceProvider.php
  lib/Reference/CommentReferenceProvider.php
  lib/Service/AttachmentService.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  lib/Service/DefaultBoardService.php
  lib/Service/FileService.php
  lib/Service/Importer/Systems/TrelloJsonService.php
  lib/Service/LabelService.php
  lib/Service/OverviewService.php
  lib/Service/PermissionService.php
  lib/Service/SessionService.php
  lib/Validators/LabelServiceValidator.php
  psalm.xml
  tests/integration/database/AssignmentMapperTest.php
  tests/integration/features/bootstrap/RequestContext.php
  tests/psalm-baseline.xml
  tests/unit/Activity/ActivityManagerTest.php
  tests/unit/Activity/DeckProviderTest.php
  tests/unit/Middleware/ExceptionMiddlewareTest.php
  tests/unit/Service/BoardServiceTest.php
  tests/unit/Service/CardServiceTest.php
  tests/unit/Service/DefaultBoardServiceTest.php
  tests/unit/Service/StackServiceTest.php
  tests/unit/controller/BoardApiControllerTest.php
  tests/unit/controller/BoardImportApiControllerTest.php
  tests/unit/controller/CardApiControllerTest.php
  tests/unit/controller/LabelApiControllerTest.php
  tests/unit/controller/PageControllerTest.php
  tests/unit/controller/StackApiControllerTest.php
Labels: bug, 3. to review

#5440 [stable25] Fix small issues around delete/undo
  .github/workflows/phpunit.yml
  lib/Collaboration/Resources/ResourceProvider.php
  lib/Db/BoardMapper.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  lib/Service/PermissionService.php
  tests/integration/base-query-count.txt
  tests/unit/Activity/ActivityManagerTest.php
Labels: bug, 3. to review

#5435 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5441 [stable28] Fix deleted card/board issues
  .github/workflows/integration.yml
  composer.json
  lib/Activity/ActivityManager.php
  lib/Activity/DeckProvider.php
  lib/Db/Card.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  lib/Service/CommentService.php
  lib/Service/PermissionService.php
  lib/Sharing/ShareAPIHelper.php
  tests/integration/features/acl.feature
  tests/integration/features/bootstrap/AttachmentContext.php
  tests/integration/features/bootstrap/BoardContext.php
  tests/integration/features/bootstrap/CommentContext.php
  tests/integration/features/bootstrap/ServerContext.php
  tests/integration/features/decks.feature
  tests/unit/Activity/DeckProviderTest.php
Labels: bug, 3. to review

#5452 also filter by storage when getting shares in folder
  lib/Sharing/DeckShareProvider.php
Labels: 3. to review, performance 🚀

#5455 Fixing #5451
  src/components/cards/CardItem.vue
Labels: bug, 3. to review

#5442 [stable27] Fix deleted card/board issues
  .github/workflows/integration.yml
  composer.json
  lib/Activity/ActivityManager.php
  lib/Activity/DeckProvider.php
  lib/Db/Card.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  lib/Service/CommentService.php
  lib/Service/PermissionService.php
  lib/Sharing/ShareAPIHelper.php
  tests/integration/features/acl.feature
  tests/integration/features/bootstrap/AttachmentContext.php
  tests/integration/features/bootstrap/BoardContext.php
  tests/integration/features/bootstrap/CommentContext.php
  tests/integration/features/bootstrap/ServerContext.php
  tests/integration/features/decks.feature
  tests/unit/Activity/DeckProviderTest.php
Labels: bug, 3. to review

#5480 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5481 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5458 fix: Add debounce to update due date
  src/components/card/CardSidebarTabDetails.vue
  src/components/card/DueDateSelector.vue
  src/views/CreateNewCardCustomPicker.vue
Labels: bug, 3. to review

#5491 fix(done): Mark card as undone when updating card
  lib/Service/CardService.php
Labels: bug, 3. to review

#5511 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5493 fixed sorting for upcoming cards
  src/components/overview/Overview.vue
Labels: bug, 3. to review

#5532 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5512 [stable28] Update nextcloud/ocp dependency
  composer.lock
  tests/integration/base-query-count.txt
Labels: 3. to review, dependencies
