Repository nextcloud/deck, pull requests merged in 2024-02, with the labels that each got.

#5533 fix(activity): Fix permission checks when rendering activities in bac…
  lib/Activity/ActivityManager.php
  lib/Activity/DeckProvider.php
Labels: bug, 3. to review

#5570 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5569 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5571 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5588 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5590 fix: Safeguard sync requests to hopefully not spam then server
  src/sessions.js
Labels: bug, 3. to review

#5537 fix: card move dialog auto close
  src/App.vue
  src/CardMoveDialog.vue
  src/components/cards/CardMenuEntries.vue
Labels: bug, 3. to review

#5603 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5610 [stable27] fix(CardMenu): introduce cardRichObject in CardMenu
  src/components/cards/CardMenu.vue
Labels: bug, frontend, 3. to review

#5604 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5623 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
