Repository nextcloud/deck, pull requests merged in 2024-04, with the labels that each got.

#5721 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5723 Clarify config file not found exception message
  lib/Service/Importer/BoardImportCommandService.php
Labels: bug, 3. to review

#5702 Fix tags' display when they are numerous
  src/components/card/TagSelector.vue
Labels: bug, design, 3. to review, ux

#5742 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5741 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5743 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5764 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5762 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5761 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5729 fix: Adapt NcAppSidebar props to new version
  src/components/card/CardSidebar.vue
Labels: bug, 3. to review, backport-request

#5790 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5794 fix: Avoid optional before required parameter
  lib/Service/ConfigService.php
Labels: bug, 3. to review, backport-request

#5818 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
