Repository nextcloud/deck, pull requests merged in 2024-06, with the labels that each got.

#5958 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5959 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5961 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#5966 chore(CI): Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#5960 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5936 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5986 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5984 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5985 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5987 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6000 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6001 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5998 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5997 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5964 fix: Adjust dependencies to fix filepicker
  package-lock.json
  package.json
  src/components/card/CardSidebar.vue
Labels: backport-request

#6027 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5999 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6028 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6011 chore: Clean up permission service
  lib/Service/PermissionService.php
  tests/unit/Service/PermissionServiceTest.php
Labels: 3. to review, technical debt

#6005 don't reset update time when no update was written to db
  src/components/card/Description.vue
Labels: bug, 3. to review

#6033 docs: Fix symlink to readme
  docs/index.md
Labels: bug, 3. to review

#6010 perf: Avoid fetching labels and owner details on permission check
  lib/Db/CardMapper.php
  lib/Service/PermissionService.php
Labels: bug, 3. to review, performance 🚀

#6038 [stable29] fix: Adjust dependencies to fix filepicker
  package-lock.json
  package.json
  src/components/board/Stack.vue
  src/components/card/AttachmentList.vue
  src/components/card/CardSidebar.vue
  src/components/cards/CardMenuEntries.vue
Labels: 3. to review, backport-request, bug: regression

#6008 chore: Move comments event handler to use proper event dispatcher
  lib/AppInfo/Application.php
  lib/Listeners/CommentEventListener.php
  tests/unit/Listeners/CommentEventListenerTest.php
Labels: 3. to review, technical debt

#6059 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
