Repository nextcloud/deck, pull requests merged in 2024-07, with the labels that each got.

#6062 Only check path for being accessible when the storage is a object home
  lib/Sharing/DeckShareProvider.php
Labels: bug, 3. to review, backport-request

#6065 fix: Remove bindParam usage with simpler query
  lib/Db/CardMapper.php
Labels: 3. to review, technical debt

#6068 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#6081 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6060 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6084 Migrate REUSE to TOML format
  .reuse/dep5
  REUSE.toml
  docs/index.md.license
Labels: 3. to review, technical debt

#6092 Backport of #5964: Fix dependencies for file picker
  cypress/e2e/cardFeatures.js
  cypress/e2e/sharingFeatures.js
  cypress/support/commands.js
  package-lock.json
  package.json
  src/App.vue
  src/CardMoveDialog.vue
  src/CardSelector.vue
  src/components/ActivityEntry.vue
  src/components/AttachmentDragAndDrop.vue
  src/components/Controls.vue
  src/components/board/BoardSidebar.vue
  src/components/board/SharingTabSidebar.vue
  src/components/board/Stack.vue
  src/components/card/AssignmentSelector.vue
  src/components/card/AttachmentList.vue
  src/components/card/CardSidebar.vue
  src/components/card/CardSidebarTabDetails.vue
  src/components/card/DueDateSelector.vue
  src/components/card/TagSelector.vue
  src/components/cards/AvatarList.vue
  src/components/cards/CardItem.vue
  src/components/cards/CardMenuEntries.vue
  src/components/cards/badges/DueDate.vue
  src/components/navigation/AppNavigation.vue
  src/components/navigation/AppNavigationAddBoard.vue
  src/components/navigation/AppNavigationBoard.vue
  src/components/navigation/AppNavigationBoardCategory.vue
  src/directives/focus.js
  src/init-reference.js
  src/views/CreateNewCardCustomPicker.vue
Labels: 3. to review, backport-request, dependencies, javascript

#6109 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6110 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6113 fix: design review issues
  css/deck.css
  src/components/ActivityEntry.vue
  src/components/Controls.vue
  src/components/SessionList.vue
  src/components/board/Board.vue
  src/components/board/BoardSidebar.vue
  src/components/board/DeletedTabSidebar.vue
  src/components/board/Stack.vue
  src/components/board/TagsTabSidebar.vue
  src/components/boards/Boards.vue
  src/components/card/AttachmentList.vue
  src/components/card/CardSidebar.vue
  src/components/card/CommentItem.vue
  src/components/card/Description.vue
  src/components/cards/CardItem.vue
  src/components/navigation/AppNavigationAddBoard.vue
  src/components/navigation/AppNavigationBoard.vue
  src/components/overview/Overview.vue
  src/components/search/Placeholder.vue
  src/css/comments.scss
  src/helpers/mentions.js
  src/helpers/xml.js
Labels: 3. to review

#6115 fix: remove redundant log
  src/init-collections.js
Labels: bug

#6129 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6141 chore: bump `1.14.0-dev` to version `1.14.0-beta.1`
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#6142 fix(files): fix appstore-build-publish.yml
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review

#6157 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6158 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6111 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
