Repository nextcloud/deck, pull requests merged in 2024-12, with the labels that each got.

#6574 fix: new card input spacing
  src/components/board/Stack.vue
Labels: bug, 3. to review

#6588 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6568 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6609 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6567 [stable28] Update nextcloud/ocp dependency
  composer.lock
  tests/integration/base-query-count.txt
Labels: 3. to review, dependencies

#6587 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6586 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6617 fix: close modal after deleting card
  src/components/cards/CardMenuEntries.vue
Labels: bug, 3. to review, backport-request, javascript, ux, skill: frontend

#6452 feat(cards): add card cloning ability
  appinfo/routes.php
  cypress/e2e/cardFeatures.js
  lib/Controller/CardController.php
  lib/Service/CardService.php
  lib/Service/LabelService.php
  src/CardMoveDialog.vue
  src/components/cards/CardMenuEntries.vue
  src/services/CardApi.js
  src/store/card.js
  tests/unit/Service/CardServiceTest.php
  tests/unit/Service/LabelServiceTest.php
Labels: enhancement, 3. to review, pending documentation

#6630 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#6628 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
