Repository nextcloud/deck, pull requests merged in 2024-08, with the labels that each got.

#6176 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6178 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6119 export json data of commments
  lib/Command/UserExport.php
  lib/Listeners/CommentEventListener.php
  lib/Service/Importer/Systems/DeckJsonService.php
  tests/integration/import/ImportExportTest.php
  tests/unit/Command/UserExportTest.php
Labels: enhancement, 2. developing, feature: export/import

#6108 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress-e2e.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#6198 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6225 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6199 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6197 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6229 fix: Reorder `info.xml` entries to make it valid
  appinfo/info.xml
Labels: bug, 3. to review

#6230 refactor: Migrate away from deprecated `ILogger` interface to PSR-3
  lib/Cron/ScheduledNotifications.php
  lib/Cron/SessionsCleanup.php
  lib/Middleware/DefaultBoardMiddleware.php
  lib/Middleware/ExceptionMiddleware.php
  lib/Service/CommentService.php
  lib/Service/FileService.php
  tests/unit/Cron/ScheduledNoificationsTest.php
  tests/unit/Middleware/ExceptionMiddlewareTest.php
  tests/unit/Service/FileServiceTest.php
Labels: 3. to review, technical debt

#6234 chore: update workflows from templates
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: 3. to review, dependencies, automated

#6255 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6256 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6254 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6253 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6235 Fix UI with the new compact design
  src/components/Controls.vue
  src/components/board/Stack.vue
  src/components/card/DueDateSelector.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardItem.vue
  src/css/selector.scss
  src/css/variables.scss
Labels: bug, design, 3. to review

#6260 Translation call fix
  src/components/SessionList.vue
Labels: bug, frontend, design, 3. to review, papercut

#6232 fix: 30 design issues
  src/App.vue
  src/CardMoveDialog.vue
  src/components/card/CardSidebar.vue
  src/components/navigation/AppNavigationBoard.vue
Labels: bug, 3. to review

#6257 copy labels when moving cards between boards
  lib/Service/CardService.php
  lib/Service/Importer/Systems/DeckJsonService.php
  tests/unit/Service/CardServiceTest.php
Labels: bug, 4. to release
