Repository nextcloud/deck, pull requests merged in 2024-03, with the labels that each got.

#5646 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5625 feat: Implement a team resource provider
  composer.lock
  img/deck-current.svg
  lib/AppInfo/Application.php
  lib/Db/BoardMapper.php
  lib/Teams/DeckTeamResourceProvider.php
Labels: enhancement, 3. to review

#5630 Interactive board widget
  package-lock.json
  package.json
  src/components/Controls.vue
  src/components/SessionList.vue
  src/components/board/Board.vue
  src/components/board/SharingTabSidebar.vue
  src/components/board/Stack.vue
  src/components/board/TagsTabSidebar.vue
  src/components/boards/BoardItem.vue
  src/components/card/CardSidebar.vue
  src/components/card/CardSidebarTabComments.vue
  src/components/card/CommentForm.vue
  src/components/card/CommentItem.vue
  src/components/card/Description.vue
  src/components/cards/AvatarList.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardItem.vue
  src/components/cards/CardMenuEntries.vue
  src/init-reference.js
  src/main.js
  src/store/main.js
  src/views/BoardReferenceWidget.vue
  src/views/CardReferenceWidget.vue
  src/views/CommentReferenceWidget.vue
Labels: enhancement, 3. to review

#5656 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5659 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5657 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5658 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5677 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5678 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5488 introduce done and open filters
  src/components/Controls.vue
  src/store/card.js
  src/store/main.js
Labels: enhancement, 2. developing

#5700 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#5703 fix: Avoid conflicts on deck attachments folder name
  lib/Service/ConfigService.php
  lib/Service/FilesAppService.php
  tests/integration/base-query-count.txt
Labels: bug, 3. to review, backport-request

#5679 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#5664 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#5720 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
