Repository nextcloud/deck, pull requests merged in 2025-01, with the labels that each got.

#6629 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6138 Feat(REST API): add url to (un)archive cards
  appinfo/routes.php
  docs/API.md
  lib/Controller/CardApiController.php
  tests/unit/controller/CardApiControllerTest.php
Labels: feedback-requested

#6430 Fixed some formatting that wasn't displaying correctly in readthedocs
  docs/User_documentation_en.md
  docs/export-import.md
Labels: feedback-requested

#5859 Update TrelloJsonService.php
  lib/Service/Importer/Systems/TrelloJsonService.php
Labels: bug, 3. to review, backport-request, feature: export/import, feedback-requested

#3430 Clone cards together with the board
  cypress/e2e/boardFeatures.js
  docs/API.md
  lib/Controller/BoardApiController.php
  lib/Controller/BoardController.php
  lib/Db/Label.php
  lib/Service/AssignmentService.php
  lib/Service/BoardService.php
  src/components/navigation/AppNavigationBoard.vue
  src/components/navigation/BoardCloneModal.vue
  src/services/BoardApi.js
  src/store/main.js
  tests/unit/Service/BoardServiceTest.php
Labels: enhancement, 2. developing

#6641 fix: Proper rich object formats
  lib/Activity/DeckProvider.php
Labels: bug, 3. to review

#6657 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6286 feat: Implement reference resolving for cards that have a link in the title
  .github/workflows/integration.yml
  cypress/e2e/cardFeatures.js
  lib/Db/Card.php
  lib/Model/CardDetails.php
  lib/Service/BoardService.php
  lib/Service/CardService.php
  src/components/card/CardSidebar.vue
  src/components/cards/CardCover.vue
  src/components/cards/CardItem.vue
  src/components/cards/CardMenu.vue
  src/components/cards/CardMenuEntries.vue
  src/store/card.js
  tests/integration/base-query-count.txt
  tests/integration/features/bootstrap/RequestContext.php
  tests/integration/import/ImportExportTest.php
  tests/unit/Db/CardTest.php
  tests/unit/Service/CardServiceTest.php
Labels: enhancement, 3. to review

#6655 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6654 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6656 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6671 fix: Properly show attachment extension
  cypress/e2e/cardFeatures.js
  src/components/card/AttachmentList.vue
  src/components/card/Description.vue
Labels: bug, 3. to review
