Repository nextcloud/deck, pull requests merged in 2025-07, with the labels that each got.

#7071 fix: ensure correct type when filtering events
  src/components/ActivityList.vue
Labels: bug, 3. to review, backport-request

#7070 fix: add retry and show warning on description saving error
  src/components/card/CardSidebar.vue
  src/components/card/Description.vue
  src/store/main.js
Labels: bug, 3. to review, backport-request

#7083 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#7107 fix: styling for new stack input field
  src/components/Controls.vue
Labels: bug, 3. to review

#7074 [main] Update nextcloud/ocp dependency
  composer.lock
  tests/integration/base-query-count.txt
Labels: 3. to review, dependencies

#7075 [stable31] Update nextcloud/ocp dependency
  composer.lock
  tests/integration/base-query-count.txt
Labels: 3. to review, dependencies

#7097 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#7120 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#7131 fix: acl check when delete, update board acl
  lib/Service/BoardService.php
Labels: backport-request

#7134 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
