Repository nextcloud/deck, pull requests merged in 2025-09, with the labels that each got.

#7135 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#7215 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6640 Feature/3331 dynamic column width
  css/deck.css
  src/components/board/Board.vue
  src/components/board/Stack.vue
  src/components/cards/CardBadges.vue
  src/components/cards/CardCover.vue
  src/components/cards/CardItem.vue
  src/components/overview/Overview.vue
  src/components/search/GlobalSearchResults.vue
  src/components/search/Placeholder.vue
  src/css/variables.scss
  src/store/card.js
Labels: enhancement, 4. to release, feedback-requested

#7159 Docs: Updating docs for API endpoints for uploading attachments
  docs/API.md
Labels: feedback-requested

#7210 Migrate delete icon to Material Symbol outline variant
  src/components/board/BoardSidebar.vue
Labels: design, 3. to review

#7238 fix(darkmode): Fix activity icon colors
  src/components/ActivityEntry.vue
Labels: bug, 3. to review, backport-request

#7231 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#7214 [stable32] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#7266 fix: redirect to cleaner URL if RewriteBase is enabled
  src/App.vue
Labels: bug, 3. to review

#7255 fix: missing push notifications
  lib/Notification/Notifier.php
  tests/integration/base-query-count.txt
Labels: bug, 3. to review

#7154 fix: parse arguments to CardService.reorder correctly to int
  lib/Controller/CardApiController.php
  lib/Service/CardService.php
Labels: feedback-requested

#7278 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
