Repository nextcloud/deck, pull requests merged in 2025-04, with the labels that each got.

#6887 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6911 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6886 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6902 Clear selected stack when selected board changed
  cypress/e2e/cardFeatures.js
  src/CardMoveDialog.vue
Labels: bug, 3. to review

#6932 fix: only delete assignments on unshared board
  lib/Db/AssignmentMapper.php
  lib/Service/BoardService.php
  tests/unit/Service/BoardServiceTest.php
Labels: bug, 3. to review, backport-request

#6947 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6898 fix: Use strings as rich object ids
  lib/Notification/Notifier.php
Labels: bug, backport-request

#6949 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6950 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6933 fix: Ensure consistent label mappings
  appinfo/info.xml
  lib/Migration/LabelMismatchCleanup.php
  lib/Service/CardService.php
  tests/unit/Service/CardServiceTest.php
Labels: bug, 3. to review, backport-request

#6916 perf: don't enrich cards when finding calendar entries
  lib/Service/CardService.php
Labels: 3. to review, feature: dav, performance 🚀

#6872 feat: add board import and export
  appinfo/routes.php
  cypress/e2e/boardFeatures.js
  cypress/fixtures/import-board.json
  lib/Controller/BoardController.php
  src/components/navigation/AppNavigation.vue
  src/components/navigation/AppNavigationBoard.vue
  src/components/navigation/AppNavigationImportBoard.vue
  src/components/navigation/BoardExportModal.vue
  src/services/BoardApi.js
  src/store/main.js
  tests/unit/Middleware/ExceptionMiddlewareTest.php
  tests/unit/controller/BoardControllerTest.php
Labels: enhancement, 3. to review
