Repository nextcloud/deck, pull requests merged in 2025-02, with the labels that each got.

#6699 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6700 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6670 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6692 fix: skip exporting a deleted card
  lib/Command/UserExport.php
  tests/unit/Command/UserExportTest.php
Labels: 2. developing, backport-request

#6720 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#6707 chore(CI): Updating npm-audit-fix.yml workflow from template
  .github/workflows/npm-audit-fix.yml
Labels: dependencies

#6718 [stable30] Update nextcloud/ocp dependency
  composer.lock
  tests/integration/base-query-count.txt
Labels: 3. to review, dependencies

#6737 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6736 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6740 feat: update default content
  REUSE.toml
  cypress/e2e/deckDashboard.js
  img/sample-image.jpg
  lib/Middleware/DefaultBoardMiddleware.php
  lib/Service/DefaultBoardService.php
  lib/Service/FilesAppService.php
  lib/Service/fixtures/default-board.json
  tests/integration/base-query-count.txt
  tests/unit/Service/DefaultBoardServiceTest.php
Labels: 3. to review

#6724 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#6768 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6769 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6770 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6790 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6791 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#6792 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
